# biography_db.py
"""
Central biographical database of key historical, patristic, classical,
and theological figures mentioned or cited in John Owen's works.
Used to automatically inject first-occurrence pop-up footnotes into the text.
"""

BIOGRAPHICAL_DB = {
    # Existing figures from technical_glossary
    "Calvin": "John Calvin (1509–1564), French theologian, pastor, and reformer during the Protestant Reformation, whose systematic theology (Reformed theology) heavily influenced Puritanism.",
    "Cyril": "Cyril of Alexandria (c. 376–444), Patriarch of Alexandria and Doctor of the Church, known for defending orthodox Christology against Nestorius at the Council of Ephesus (431).",
    "Charnock": "Stephen Charnock (1628–1680), English Puritan Presbyterian theologian, celebrated for his classic treatise on the existence and attributes of God.",
    "Augustine": "Augustine of Hippo (354–430), influential Latin church father and bishop whose writings on grace, original sin, the Trinity, and ecclesiology shaped Western Christian theology.",
    "Chrysostom": "John Chrysostom (c. 347–407), Archbishop of Constantinople and Doctor of the Church, famed for his eloquent preaching, biblical homilies, and liturgical revisions.",
    "Athanasius": "Athanasius of Alexandria (c. 296–373), bishop of Alexandria and Doctor of the Church, renowned for defending the deity of Christ and the Trinity against Arianism.",
    "Erasmus": "Desiderius Erasmus of Rotterdam (1466–1536), Dutch Christian humanist and scholar who published the first print Greek New Testament, laying groundwork for Reformation scholarship.",
    "Socinus": "Faustus Socinus (1539–1604), Italian rationalist theologian who denied the Trinity, the pre-existence and deity of Christ, and penal substitutionary atonement.",
    "Bellarmine": "Robert Bellarmine (1542–1621), Italian Jesuit cardinal and theologian, who was the preeminent Roman Catholic apologist of the Counter-Reformation.",
    "Vorstius": "Conrad Vorstius (1569–1622), German-Dutch theologian accused of Socinianism and heterodoxy, whose appointment at Leiden was opposed by King James I.",
    "Ussher": "James Ussher (1581–1656), Archbishop of Armagh and Primate of All Ireland, renowned scholar who formulated the Ussher chronology of biblical history.",
    "Grotius": "Hugo Grotius (1583–1645), Dutch jurist, statesman, and theologian, who advanced the governmental theory of the atonement and pioneered modern international law.",
    "Arminius": "Jacobus Arminius (1560–1609), Dutch theologian whose critique of Reformed views on predestination led to the Remonstrant (Arminian) movement.",

    # Patristic & Classical Authors from patristic_refs
    "Basil": "Basil of Caesarea (c. 330–379), also called Basil the Great, Bishop of Caesarea and Doctor of the Church, who defended Nicene orthodoxy against Arianism and pioneered communal monasticism.",
    "Eusebius": "Eusebius of Caesarea (c. 260–339), Bishop of Caesarea, historian, and exegete, often called the 'Father of Church History' for his landmark work Historia Ecclesiastica.",
    "Ambrose": "Ambrose of Milan (c. 339–397), Bishop of Milan and Doctor of the Church, famed for his ecclesiastical administration, sermons, and role in Augustine's conversion.",
    "Hilary": "Hilary of Poitiers (c. 310–367), Bishop of Poitiers and Doctor of the Church, called the 'Malleus Arianorum' (Hammer of the Arians) for his fierce defense of Nicene Christology.",
    "Jerome": "Jerome (Hieronymus) (c. 347–420), Latin church father and Doctor of the Church, best known for translating the Bible into Latin (the Vulgate) and for his biblical commentaries.",
    "Origen": "Origen of Alexandria (c. 184–253), influential early Christian scholar, theologian, and exegete, known for his allegorical biblical interpretation and vast textual studies like the Hexapla.",
    "Tertullian": "Tertullian (c. 155–220), prolific early Christian author from Carthage, often called the 'Father of Western Theology' for coining the Latin terminology of the Trinity.",
    "Cyprian": "Cyprian of Carthage (c. 200–258), Bishop of Carthage and influential Latin writer, known for his writings on the unity of the Church and his martyrdom under Valerian.",
    "Epiphanius": "Epiphanius of Salamis (c. 315–403), Bishop of Salamis and heresy hunter, whose chief work, the Panarion, lists and refutes eighty heresies from antiquity.",
    "Irenaeus": "Irenaeus of Lyon (c. 130–202), Bishop of Lugdunum (Lyon) and early Christian apologist, whose treatise Adversus Haereses (Against Heresies) systematically refuted Gnosticism.",
    "Prosper": "Prosper of Aquitaine (c. 390–455), Latin Christian writer and disciple of Augustine, who defended the Augustinian doctrine of grace against semi-Pelagianism.",
    "Gregory of Nazianzus": "Gregory of Nazianzus (c. 329–390), Archbishop of Constantinople and theologian, famed for his Five Theological Orations defending the deity of the Son and Holy Spirit.",
    "Gregory of Nyssa": "Gregory of Nyssa (c. 335–395), Bishop of Nyssa and brother of Basil, key theologian of the Trinity who contributed to the Nicene-Constantinopolitan Creed.",
    "Lactantius": "Lactantius (c. 250–325), early Christian author and advisor to Constantine, known as the 'Christian Cicero' for his elegant defense of Christianity in his Divine Institutes.",
    "Theodoret": "Theodoret of Cyrrhus (c. 393–457), influential bishop, theologian, and historian of the school of Antioch, known for his Christological writings and biblical commentaries.",
    "Socrates Scholasticus": "Socrates Scholasticus (c. 380–440), Greek church historian whose Ecclesiastical History covers the history of the early Church from 305 to 439.",
    "Leo the Great": "Leo I (c. 400–461), Pope and Doctor of the Church, whose Tome of Leo defined orthodox Christological doctrine (two natures in one person) for the Council of Chalcedon.",
    "Maximus": "Maximus of Turin (c. 380–420), Bishop of Turin and early Christian writer, known for his numerous short homilies on liturgical, ethical, and biblical topics.",
    "Didymus": "Didymus the Blind (c. 313–398), Alexandrian theologian and head of the Catechetical School of Alexandria, admired for his theological treatises on the Holy Spirit and the Trinity.",
    "Novatian": "Novatian (c. 200–258), Roman theologian, writer, and early antipope, who taught strict discipline regarding the lapsed and wrote the landmark De Trinitate.",
    "Aristotle": "Aristotle (384–322 BC), classical Greek philosopher and polymath, whose works on logic, metaphysics, ethics, and physics profoundly shaped medieval Scholasticism.",
    "Plato": "Plato (c. 428–348 BC), classical Greek philosopher, founder of the Academy, whose theory of Forms and dialogues heavily influenced early Christian theology and Neoplatonism.",
    "Cicero": "Marcus Tullius Cicero (106–43 BC), Roman statesman, orator, and philosopher, whose writings on rhetoric, duty, and politics influenced Western humanist education.",
    "Virgil": "Publius Vergilius Maro (70–19 BC), classical Roman poet, author of the Eclogues, Georgics, and the epic Aeneid, widely read throughout Christian antiquity and the Middle Ages.",
    "Horace": "Quintus Horatius Flaccus (65–8 BC), leading Roman lyric poet of the Augustan era, famed for his Satires, Epistles, and Odes.",
    "Seneca": "Lucius Annaeus Seneca (c. 4 BC–65 AD), Roman Stoic philosopher, statesman, and dramatist, whose moral letters to Lucilius were highly regarded by early Christian writers.",
    "Varro": "Marcus Terentius Varro (116–27 BC), prolific ancient Roman scholar and writer, whose works covered agriculture, language, and Roman antiquities.",
    "Livy": "Titus Livius (Livy) (c. 59 BC–17 AD), Roman historian who wrote Ab Urbe Condita Libri, a monumental history of Rome and its people.",
    "Plutarch": "Plutarch (c. 46–119 AD), Greek philosopher, biographer, and essayist, famed for his Parallel Lives comparing Greek and Roman figures.",
    "Aquinas": "Thomas Aquinas (1225–1274), Italian Dominican friar, Doctor of the Church, and the preeminent Scholastic theologian, whose Summa Theologiae synthesized Aristotelianism and Christian theology.",
    "Petavius": "Denis Pétau (Petavius) (1583–1652), French Jesuit theologian and scholar, whose monumental De Theologicis Dogmatibus pioneered the history of Christian dogma.",
    "Montacutius": "Richard Montague (Montacutius) (1577–1641), controversial Arminian Anglican bishop and scholar, known for his anti-Puritan treatises and patristic studies.",
    "Melchior Cano": "Melchior Cano (1509–1560), Spanish Dominican theologian, bishop, and Scholastic scholar, whose De Locis Theologicis established a methodology for theological authorities.",
    "Sozomen": "Salminius Hermias Sozomen (c. 400–450), Christian historian of Palestine, whose Ecclesiastical History covers the period from Constantine to Theodosius II.",
    "John of Damascus": "John of Damascus (c. 675–749), Syrian monk, priest, and Doctor of the Church, whose De Fide Orthodoxa systematically summarized Eastern patristic theology.",
    "Bernard": "Bernard of Clairvaux (1090–1153), French Cistercian abbot, reformer, and mystic, known for his monastic theology and role in reviving the Cistercian order.",
    "Constantine": "Constantine I (272–337 AD), first Roman emperor to convert to Christianity, who issued the Edict of Milan (313) and convoked the Council of Nicaea (325).",
    "Ephraim": "Ephraim Syrus (Ephrem the Syrian) (c. 306–373), Syriac deacon, hymnwriter, and theologian, renowned for his theological poetry and defenses of the Trinity.",
    "Fulgentius": "Fulgentius of Ruspe (468–533), Bishop of Ruspe in North Africa, a leading defender of Augustinian theology against semi-Pelagianism and Arianism.",
    "Clement of Alexandria": "Clement of Alexandria (c. 150–215), Christian theologian and head of the Catechetical School of Alexandria, who sought to harmonize Greek philosophy with Christian faith.",
    "Theophylact": "Theophylact of Ohrid (c. 1055–1107), Byzantine Archbishop of Ohrid, famed for his clear biblical commentaries which were highly regarded by both Catholic and Protestant reformers.",
    "Cassiodorus": "Marcus Aurelius Cassiodorus (c. 485–585), Roman statesman and writer, who established the Vivarium monastery where monks preserved classical and theological texts.",
    "Theophanes": "Theophanes the Confessor (c. 758–818), Byzantine monk and chronicler, whose Chronicle is a primary historical source for Byzantine history.",
    "Peter Chrysologus": "Peter Chrysologus (c. 380–450), Bishop of Ravenna and Doctor of the Church, famed for his short, eloquent homilies, earning him the name 'Golden-worded' (Chrysologus).",
    "Rufinus": "Rufinus of Aquileia (c. 344–411), Latin monk, historian, and translator, who translated Origen's works and Eusebius's Ecclesiastical History into Latin.",
    "Pliny": "Pliny the Younger (61–c. 113 AD), Roman lawyer and author, whose letters to Trajan contain the earliest non-Christian description of Christian worship.",
    "Ignatius": "Ignatius of Antioch (c. 35–108 AD), Bishop of Antioch, who wrote a series of seven letters on ecclesiology, church order, and theology while en route to his martyrdom in Rome.",
    "Tacitus": "Publius Cornelius Tacitus (c. 56–120 AD), Roman historian and senator, whose Annals and Histories document the reigns of early emperors and contain early references to Christ.",
    "Justin": "Justin (Marcus Junianus Justinus), 2nd or 3rd-century Roman historian who compiled an epitome of the historical works of Pompeius Trogus.",
    "Thucydides": "Thucydides (c. 460–400 BC), Athenian historian and general, whose History of the Peloponnesian War pioneered scientific, evidence-based historical writing.",
    "Herodian": "Herodian of Antioch (c. 170–240 AD), Greek historian who wrote a history of the Roman Empire from the death of Marcus Aurelius to the accession of Gordian III.",
    "Josephus": "Flavius Josephus (37–c. 100 AD), Jewish historian and apologist, whose Jewish Antiquities and The Jewish War are critical sources for first-century Jewish history.",
    "Glassius": "Salomo Glassius (1593–1656), German Lutheran theologian and biblical scholar, whose Philologia Sacra was a classic textbook on biblical hermeneutics and language.",
    "Drusius": "Johannes Drusius (1550–1616), Flemish Protestant divine and distinguished Semitic scholar, known for his studies on biblical antiquities and Hebrew philology.",
    "Volkelius": "Johannes Volkelius (c. 1560–1618), German Socinian theologian and writer, whose De Vera Religione (1630) was a comprehensive systematic theology of Socinianism.",
    "Stapleton": "Thomas Stapleton (1535–1598), English Roman Catholic controversialist and theologian, who defended Catholic authority against Protestant reformers from Louvain.",
    "Mantuanus": "Baptista Mantuanus (1447–1516), Italian Carmelite reformer and humanist poet, whose Latin eclogues were widely used in European school curricula.",
    "Episcopius": "Simon Episcopius (1583–1643), Dutch theologian and professor, who draft the Remonstrance of 1610 and became the principal defender of Arminianism after Arminius.",
    "Sixtinus Amama": "Sixtinus Amama (1593–1629), Dutch Reformed theologian and Semitic linguist, who advocated for the study of biblical languages for ministers.",
    "Xenophon": "Xenophon (c. 430–354 BC), classical Greek historian, philosopher, and student of Socrates, famed for his Anabasis and Cyropaedia.",
    "Dionysius": "Dionysius of Halicarnassus (c. 60–7 BC), Greek historian and teacher of rhetoric, whose Roman Antiquities detailed the early history of Rome.",
    "Rainolds": "John Rainolds (1549–1607), English Puritan scholar and President of Corpus Christi College, Oxford, who initiated the proposal for the King James Bible translation.",
    "Rivet": "André Rivet (1572–1651), French Huguenot theologian and professor of theology at Leiden, known for his polemical treatises and biblical commentaries.",
    "Scultetus": "Abraham Scultetus (1566–1624), German Reformed theologian, professor of theology at Heidelberg, and court preacher to Frederick V.",
    "Dio Cassius": "Dio Cassius (c. 155–235 AD), Roman consul and historian, who wrote a monumental 80-volume history of Rome in Greek.",
    "Hulsius": "Antonius Hulsius (1615–1685), German-Dutch Reformed theologian and Hebrew scholar, who wrote on Semitic languages and defended biblical reliability.",
    "Galatinus": "Petrus Galatinus (1460–1540), Italian Franciscan friar, Jewish convert, and polemicist, whose De Arcanis Catholicae Veritatis defended Christianity using Rabbinic sources.",
    "Martial": "Marcus Valerius Martialis (Martial) (c. 38–104 AD), Roman poet from Hispania, famous for his twelve books of Epigrams satirizing Roman life.",
    "Sarnicki": "Stanisław Sarnicki (1532–1597), Polish Reformed theologian, historian, and military writer, who studied under Calvin and Melanchthon.",
    "Zanchi": "Girolamo Zanchi (1516–1590), Italian Reformed Scholastic theologian, who taught at Strasbourg and Heidelberg, known for his meticulous treatises on God's nature and predestination.",
    "Scribani": "Carolus Scribani (Clarus Bonarus) (1561–1629), Belgian Jesuit theologian, administrator, and writer, known for his polemical and ascetical works.",
    "Mendoza": "Franciscus de Mendoza (1573–1626), Spanish Jesuit theologian, scholar, and professor of Scripture, known for his erudite commentaries on the Books of Kings.",
    "Paterculus": "Velleius Paterculus (c. 19 BC–31 AD), Roman soldier and historian, who wrote an epitome of Roman history from the Trojan War to the death of Livia.",
    "Servius": "Servius Maurus Honoratus, late 4th-century Roman grammarian and commentator, famous for his detailed commentaries on the works of Virgil.",
    "Stobaeus": "Joannes Stobaeus (5th century AD), Greek compiler and anthologist, who collected extracts from over 500 classical writers, preserving many lost works.",
    "Albo": "Joseph Albo (c. 1380–1444), Spanish Jewish rabbi, philosopher, and apologist, famous for his Sefer ha-Ikkarim (Book of Principles) on Jewish dogma.",
    "Raemond": "Florimond de Raemond (c. 1540–1601), French jurist and historian, who wrote a Catholic history of the Reformation defending Catholic tradition.",
    "Connan": "François Connan (1508–1551), French jurist and humanist scholar, who pioneered modern legal theory in his Commentaria Juris Civilis.",
    "Menochius": "Jacopo Menochio (1532–1607), prominent Italian jurist, judge, and legal scholar, famed for his authoritative works on legal presumptions and civil law.",
    "Pighius": "Albert Pighius (c. 1490–1542), Dutch Catholic theologian and controversialist, who defended free will and the papacy in debates with John Calvin.",
    "Cappel": "Louis Cappel (1585–1658), French Huguenot divine, Hebrew scholar, and professor at Saumur, famous for showing the Hebrew vowel points were post-biblical.",
    "Morinus": "Jean Morin (Morinus) (1591–1659), French theologian, oratorian, and biblical scholar, who edited the Paris Polyglot and wrote on the Samaritan Pentateuch.",
    "Johannes Isaac": "Johannes Isaac (1515–1597), Jewish convert to Catholicism, grammarian, and professor of Hebrew at Cologne, known for his defenses of Hebrew grammar.",
    "Fuller": "Nicholas Fuller (1557–1626), English Hebraist, philologist, and prebendary of Salisbury, whose Miscellanea Sacra explored biblical antiquities.",
    "Azariah": "Azariah de' Rossi (c. 1511–1578), Italian Jewish physician and scholar, whose Me'or Einayim critically evaluated Jewish history and chronology using classical sources.",
    "Justinian": "Justinian I (482–565 AD), Eastern Roman Emperor famed for reorganizing Roman law in the Corpus Juris Civilis, which shaped subsequent European jurisprudence.",
    "Plotinus": "Plotinus (c. 204–270 AD), Hellenistic philosopher born in Egypt, the founder of Neoplatonism, whose concepts of the 'One' influenced early Christian theology.",

    # New prominent figures detected from scanning volume text
    "Baxter": "Richard Baxter (1615–1691), English Puritan churchman, pastor, and theologian, whose moderate Reformed views (Amyraldianism) and pastoral classic The Reformed Pastor were highly influential.",
    "Justin Martyr": "Justin Martyr (c. 100–165 AD), early Christian apologist, philosopher, and martyr, whose First and Second Apologies defended Christian theology and worship against Roman paganism.",
    "Simon Magus": "Simon Magus (Simon the Sorcerer), a first-century Samaritan magician mentioned in Acts 8:9–24, traditionally identified in patristic literature as the archetype of all heretics.",
    "Biddle": "John Biddle (1615–1662), English schoolmaster and theologian, often called the 'Father of English Unitarianism' for his anti-Trinitarian tracts and teachings.",
    "Arias Montanus": "Benedictus Arias Montanus (1527–1598), Spanish Benedictine orientalist, scholar, and diplomat, who edited the landmark Antwerp Polyglot Bible (1569–1572).",
    "Thomas More": "Thomas More (1478–1535), English humanist scholar, statesman, and Chancellor of England, who opposed the Protestant Reformation and was executed for refusing to acknowledge Henry VIII as Supreme Head of the Church.",
    "Paulus Samosatenus": "Paul of Samosata (Paulus Samosatenus) (200–275 AD), Bishop of Antioch, who was deposed for heresy (Adoptionist Monarchianism) for teaching that Jesus was a mere man filled with the Word of God.",
    "Pontius Pilate": "Pontius Pilate, Roman prefect of Judea (26–36 AD) under Emperor Tiberius, who presided over the trial of Jesus Christ and authorized His crucifixion.",
    "Orme": "William Orme (1787–1830), Scottish Congregational minister and biographer, who wrote the first comprehensive biography of John Owen (Memoirs of the Life, Writings, and Religious Connections of John Owen, D.D.) in 1820.",
    "Hammond": "Henry Hammond (1605–1660), pioneering English Anglican churchman, chaplain to Charles I, and theologian, celebrated for his Paraphrase and Annotations on the New Testament.",
    "Smalcius": "Valentin Schmalz (Valentinus Smalcius) (1572–1622), German-Polish Socinian writer and theologian, who helped draft the Racovian Catechism (1605) and defended anti-Trinitarianism.",
    "John Asty": "John Asty (c. 1675–1730), an English Independent minister who wrote the first memoir of John Owen's life prefixed to the 1721 folio edition of Owen's sermons.",
    "John Nesbitt": "John Nesbitt (1661–1727), an English Independent minister in London who co-edited the 1721 folio edition of John Owen's posthumous sermons and tracts.",
    "Matthew Clarke": "Matthew Clarke (1664–1726), a prominent English Independent minister and co-editor of the 1721 folio edition of John Owen's sermons.",
    "Thomas Ridgley": "Thomas Ridgley (c. 1667–1734), an English Independent minister, theologian, and tutor who wrote A Body of Divinity and co-edited the 1721 folio edition of John Owen's sermons.",
    "Thomas Bradbury": "Thomas Bradbury (1677–1759), a zealous and witty English Dissenting minister in London, known for his defense of the doctrine of the Trinity and co-editing the 1721 folio edition of John Owen's sermons.",
    "Andrew Thomson": "Andrew Thomson (1779–1831), a prominent Scottish Presbyterian minister and author of a highly regarded biography of John Owen published in 1850.",
    "Nestorius": "Nestorius (c. 386–c. 450), Archbishop of Constantinople, whose Christological views (deemed to divide Christ into two persons) were condemned at the Council of Ephesus (431).",
    "Eutyches": "Eutyches (c. 380–c. 456), an archimandrite in Constantinople, whose extreme opposition to Nestorius led him to teach that Christ's human and divine natures were fused into one, condemned at the Council of Chalcedon (451).",
    "John Goodwin": "John Goodwin (1594–1665), an influential English Arminian Puritan minister, theologian, and republican pamphleteer, against whose Arminian doctrines John Owen wrote several major treatises.",
    "Thomas Goodwin": "Thomas Goodwin (1600–1680), a leading Puritan Congregational theologian, close associate of John Owen, and chaplain to Oliver Cromwell.",
    "Isaac Chauncy": "Isaac Chauncy (1635–1712), a nonconformist physician and Independent minister in London who succeeded John Owen as pastor of the Mark Lane congregation in 1687.",
    "Isaac Watts": "Isaac Watts (1674–1748), a famous English Congregational minister, theologian, and prolific hymn writer ('Father of English Hymnody') who succeeded Isaac Chauncy in 1702 as pastor of the Mark Lane congregation.",
    "Sir John Hartopp": "Sir John Hartopp (1637–1722), an English baronet, Member of Parliament, and close friend of John Owen who attended his ministry and preserved his sermons in short-hand notes.",
    "Dr. Wright": "George Wright (D.D., d. 1827), a minister of the Established Church in Stirling, Scotland, who produced a highly regarded edition of John Owen's Exposition of the Epistle to the Hebrews.",
    "George Bull": "George Bull (1634–1710), Bishop of St Davids and eminent Anglican theologian, renowned for his Defensio Fidei Nicaenae defending the Nicene doctrine of the Trinity.",
    "William Sherlock": "William Sherlock (c. 1641–1707), Dean of St Paul's and English churchman, whose Vindication of the Doctrine of the Holy and Ever Good Trinity sparked intense controversy.",
    "Robert South": "Robert South (1634–1716), a celebrated English churchman and orator, known for his vigorous opposition to William Sherlock's Trinitarian views, which he accused of tritheism.",
    "William Whiston": "William Whiston (1667–1752), an English mathematician and theologian who succeeded Isaac Newton at Cambridge, expelled for his advocacy of Arianism.",
    "James Peirce": "James Peirce (1673–1726), a prominent Presbyterian Dissenting minister in Exeter, ejected from his pulpit during the Salters' Hall controversy for his Arian views.",
    "Joseph Hallet": "Joseph Hallett II (1656–1722), a Presbyterian Dissenting minister in Exeter associated with James Peirce in the Arian controversy.",
    "Samuel Clarke": "Samuel Clarke (1675–1729), an influential English philosopher and Anglican theologian who published The Scripture-Doctrine of the Trinity in 1712, accused of Arianism.",
    "William Payne": "William Payne (c. 1650–1696), a member and leader in John Owen's Mark Lane congregation who saw Owen's final work, Meditations on the Glory of Christ, to the press on the day of Owen's death.",
    "Simon Commenicq": "Simon Commenicq, an opulent Dutch merchant in Rotterdam who translated John Owen's Exposition of the Epistle to the Hebrews into Dutch (published in 1733–1740).",
    "James Hervey": "James Hervey (1714–1758), an English clergyman and popular writer, author of Theron and Aspasio, who wrote highly of John Owen's Meditations on the Glory of Christ.",
    "Richard Cecil": "Richard Cecil (1748–1810), an influential evangelical Anglican priest in London and member of the Eclectic Society, who praised John Owen's works for theological depth.",
    "William Steven": "William Steven (1796–1857), a Scottish minister and author of The History of the Scottish Church, Rotterdam (1832), who documented continental translations of Owen's works.",
    "William Baynes": "William Baynes, a prominent London publisher who undertook the publication of the first major uniform edition of John Owen's works in 1826.",
    "David Bogue": "David Bogue (1750–1825), a Scottish missionary and Congregational minister who co-authored the History of Dissenters, praising the Puritan school of theology.",
    "James Bennett": "James Bennett (1774–1862), an English Congregational minister who co-authored the History of Dissenters alongside David Bogue.",
    "Theodore Beza": "Theodore Beza (1519–1605), a French Protestant Christian theologian, reformer, and scholar who succeeded John Calvin as the leader of the Reformed church in Geneva.",
    "Johannes Crellius": "Johannes Crellius (John Crell) (1590–1633), a prominent German-Polish Socinian theologian, writer, and rector of the Racovian Academy, known for his biblical commentaries and ethical treatises.",
    "Franciscus David": "Ferenc Dávid (Franciscus Davidis) (c. 1510–1579), a Hungarian Unitarian theologian and bishop, who advocated non-adorantism (denying that Christ should be addressed in prayer), which Faustus Socinus strongly opposed.",
    "Christianus Franken": "Christian Franken (1549–c. 1602), a German writer who was successively a Jesuit, Unitarian, and critic of Socinus, famous for his disputation with Socinus regarding the adoration of Christ.",
    "Matthias Radecius": "Mateusz Radecke (Matthias Radecius) (d. 1612), a Polish Socinian writer and secretary of the city of Danzig, who defended Socinian views.",
    "Jonas Schlichtingius": "Jonasz Szlichtyng (Jonas Schlichtingius) (1592–1661), a leading Polish Socinian theologian, scholar, and writer, who authored the Socinian confession of faith and extensive biblical commentaries.",
    "Gregorius Pauli": "Grzegorz Paweł of Brzeziny (Gregorius Pauli) (c. 1525–1591), an early leader of the Polish Brethren (Antitrinitarians) who advocated radical social egalitarianism and antitrinitarianism.",
    "Nicolaus Arnoldus": "Nicholas Arnold (Nicolaus Arnoldus) (1618–1680), a Polish-born Dutch Reformed theologian and professor at Franeker, renowned for his polemical treatises against Socinianism.",
    "Prince Radzivil": "Mikołaj Radziwiłł 'the Black' (1515–1565), a powerful Polish-Lithuanian nobleman and reformer who sponsored the Brest Bible (Radziwiłł Bible) and patronized the Reformed church.",
    "Paulus Alciatus": "Giovanni Paolo Alciati (d. c. 1573), an Italian physician and antitrinitarian who fled to Switzerland and then Poland, joining the early antitrinitarian movement.",
    "Bernardus Ochinus": "Bernardino Ochino (1487–1564), a famous Italian Capuchin reformer who converted to Protestantism, preached in England and Switzerland, and later published dialogues containing antitrinitarian views.",
    "Erasmus Johannes": "Erasmus Johannis (d. c. 1590), a Dutch Unitarian theologian and schoolmaster who debated Faustus Socinus regarding the pre-existence of Christ.",
    "Daniel Bielenscius": "Daniel Bieliński (Daniel Bielenscius) (16th century), a Polish Antitrinitarian leader who initially held radical 'Judaizing' views but later repented and returned to the Reformed faith.",
    "Sibrandus Lubbertus": "Sibrand Lubbert (Sibrandus Lubbertus) (c. 1555–1625), a Dutch Reformed theologian and professor at Franeker who wrote polemics against Faustus Socinus and Conrad Vorstius.",
    "Michael Gitichius": "Michał Gittich (Michael Gitichius) (d. 1654), a Polish Socinian minister and writer who was later excommunicated from the Socinian community for his radical views.",
    "Ludovicus Lucius": "Ludwig Lucius (Ludovicus Lucius) (1577–1642), a Swiss Reformed theologian and professor of logic and theology at Basel, who wrote against Socinian doctrine.",
    "Martin Seidelius": "Martin Seidel (Martin Seidelius) (d. c. 1612), a German antitrinitarian who advocated a form of deism denying the authority of the New Testament and the messiahship of Christ.",
    "Simon Ronembergius": "Simon Ronemberg (Simon Ronembergius), a prominent Polish pharmacist, elder, and patron of the Socinian congregation in Kraków and Raków.",
    "Adam Neuserus": "Adam Neuser (Adam Neuserus) (c. 1530–1576), a German Reformed pastor in Heidelberg who converted to Antitrinitarianism and ultimately fled to the Ottoman Empire, where he converted to Islam.",
    "Andreas Wengerscius": "Andreas Węgierski (Adrian Regenvolscius) (1600–1649), a Polish Reformed minister and church historian who documented the history of the Slavic Protestant churches.",
    "Christophorus Ostorodius": "Christoph Ostorodt (Christophorus Ostorodius) (d. 1611), a German-born Polish Socinian minister and writer, who co-authored a major Socinian catechism.",
    "Andreas Voidovius": "Andrzej Wojdowski (Andreas Voidovius) (1565–1622), a Polish Socinian writer and theologian who traveled widely in Western Europe promoting antitrinitarianism.",
    "George Blandrata": "Giorgio Biandrata (George Blandrata) (1515–1588), an Italian physician and court theologian in Poland and Transylvania who was a leading organizer of the antitrinitarian churches.",
    "Peter Statorius": "Pierre Statorius (Peter Statorius) (d. 1591), a French-born reformer and grammarian who became a Socinian minister in Poland and wrote the first grammar of the Polish language.",
    "Conrad Schlusselburg": "Conrad Schlüsselburg (Conradus Schlusselburgius) (1543–1619), a German Lutheran theologian, co-author of the Formula of Concord, who wrote extensively against Calvinism and various heresies.",
    "Stephen Gerlach": "Stephen Gerlach (Stephanus Gerlachius) (1546–1612), a German Lutheran theologian, preacher, and professor at Tübingen, known for his diary of his travels to Constantinople.",
    "St Austin": "Augustine of Hippo (354–430), influential Latin church father and bishop whose writings on grace, original sin, the Trinity, and ecclesiology shaped Western Christian theology.",
    "Austin": "Augustine of Hippo (354–430), influential Latin church father and bishop whose writings on grace, original sin, the Trinity, and ecclesiology shaped Western Christian theology.",
    "Hierom": "Jerome (Hieronymus) (c. 347–420), Latin church father and Doctor of the Church, best known for translating the Bible into Latin (the Vulgate) and for his biblical commentaries.",
    "Hierome": "Jerome (Hieronymus) (c. 347–420), Latin church father and Doctor of the Church, best known for translating the Bible into Latin (the Vulgate) and for his biblical commentaries.",
    "Schlictingius": "Jonasz Szlichtyng (Jonas Schlichtingius) (1592–1661), a leading Polish Socinian theologian, scholar, and writer, who authored the Socinian confession of faith and extensive biblical commentaries.",
    "Schlichtingius": "Jonasz Szlichtyng (Jonas Schlichtingius) (1592–1661), a leading Polish Socinian theologian, scholar, and writer, who authored the Socinian confession of faith and extensive biblical commentaries.",
    "Junius": "Francis Junius the Elder (1545–1602), a French Reformed theologian who was professor at Heidelberg and Leiden, famous for his Latin translation of the Old Testament with Tremellius, and for his theological works.",
    "Suarez": "Francisco Suárez (1548–1617), a Spanish Jesuit priest, philosopher, and theologian, one of the leading figures of the School of Salamanca and generally regarded as among the greatest scholastics after Thomas Aquinas.",
    "Maldonate": "Juan de Maldonado (Johannes Maldonatus, 1533–1583), a Spanish Jesuit theologian and exegete, famous for his commentaries on the Gospels.",
    "Rutherford": "Samuel Rutherford (c. 1600–1661), a Scottish Presbyterian theologian and Covenanter, professor of divinity at St Andrews, known for his political treatise Lex, Rex and his spiritual letters.",
    "Whitaker": "William Whitaker (1548–1595), an English Reformed theologian and Master of St John's College, Cambridge, a prominent defender of the Reformed faith against Roman Catholicism.",
    "Cameron": "John Cameron (c. 1579–1625), a Scottish Reformed theologian who spent much of his life in France, professor at Saumur, founder of the Saumur school of moderate Calvinism.",
    "Amyraldus": "Moses Amyraut (Moisy Amyraut, Moses Amyraldus, 1596–1664), a French Protestant theologian, professor at Saumur, known for his doctrine of Amyraldianism (hypothetical universalism).",
    "Ames": "William Ames (Guilielmus Amesius, 1576–1633), an English Puritan theologian, philosopher, and professor at Franeker in the Netherlands, famous for his Medulla Theologiae (The Marrow of Sacred Divinity).",
    "Cranmer": "Thomas Cranmer (1489–1556), Archbishop of Canterbury and leader of the English Reformation, who compiled the Book of Common Prayer and was martyred under Queen Mary.",
    "Altingius": "Johann Heinrich Alting (1583–1644), a German Reformed theologian, professor at Heidelberg and Groningen, who represented the Palatinate at the Synod of Dort.",
    "Chamier": "Daniel Chamier (1565–1621), a French Reformed theologian and writer, one of the key drafters of the Edict of Nantes, famous for his massive anti-Catholic work Panstratia Catholica.",
    "Davenant": "John Davenant (1572–1641), Bishop of Salisbury, English Reformed theologian and delegate to the Synod of Dort, who advocated hypothetical universalism.",
    "Cartwright": "Thomas Cartwright (c. 1535–1603), an English Puritan churchman, academic, and theologian, widely regarded as a major developer of English Presbyterianism.",
    "Macovius": "Johannes Maccovius (Jan Makowski, 1588–1644), a Polish Reformed theologian and professor of theology at Franeker, known for his high Calvinist scholasticism.",
    "Jansenius": "Cornelius Jansen (Cornelius Jansenius, 1585–1638), Bishop of Ypres, Dutch Catholic theologian whose book Augustinus initiated the Jansenist movement inside the Roman Catholic Church.",
    "Spanhemius": "Friedrich Spanheim the Elder (1600–1649), a German-born Reformed theologian, professor at Geneva and Leiden, who defended orthodox Calvinism.",
    "Kortholt": "Christian Kortholt (1633–1694), a German Lutheran theologian and writer, professor of Greek and theology at Kiel.",
    "Walaeus": "Antonius Walaeus (1573–1639), a Dutch Reformed theologian, delegate to the Synod of Dort, and professor of theology at Leiden.",
    "Bailie": "Robert Baillie (Bailie, 1602–1662), a Scottish Presbyterian minister, Covenanter, delegate to the Westminster Assembly, and Principal of the University of Glasgow.",
    "Canes": "John Vincent Canes (d. 1672), a Flemish-born English Franciscan friar and controversialist, who wrote the pro-Catholic work Fiat Lux, to which John Owen wrote a detailed reply.",
    "Walton": "Brian Walton (1600–1661), English bishop and scholar, famous for compiling the monumental London Polyglot Bible (Biblia Polyglotta, 1657), which John Owen criticized in his Considerations on the Polyglot.",
    "Cromwell": "Oliver Cromwell (1599–1658), English statesman and military leader who served as Lord Protector of the Commonwealth of England, Scotland, and Ireland; a patron of John Owen.",
    "Charles II": "Charles II (1630–1685), King of Great Britain and Ireland from the Restoration of the monarchy in 1660 until his death, whose reign saw major religious conflicts and nonconformist persecution.",

    # Volume 2 Expansion Figures
    "Thomas Danson": "Thomas Danson (c. 1629–1694), an ejected Presbyterian minister and controversialist who wrote several works against Quakerism and Arminianism.",
    "Lewis Stucley": "Lewis Stucley (Stuckley) (c. 1621–1687), an English Independent minister ejected from Exeter Cathedral in 1660, noted for his works on spiritual gospel-walk.",
    "Lewis Stuckley": "Lewis Stucley (Stuckley) (c. 1621–1687), an English Independent minister ejected from Exeter Cathedral in 1660, noted for his works on spiritual gospel-walk.",
    "Daniel Burgess": "Daniel Burgess (1645–1713), a prominent Presbyterian minister in London known for his lively, humorous preaching style and courage during persecution.",
    "Quintus Curtius": "Quintus Curtius Rufus, a 1st-century Roman historian who wrote the only surviving Latin biography of Alexander the Great.",
    "Quintus Curtius Rufus": "Quintus Curtius Rufus, a 1st-century Roman historian who wrote the only surviving Latin biography of Alexander the Great.",
    "Thomas Sherlock": "Thomas Sherlock (1678–1761), Bishop of London, a prominent Anglican writer and apologist who defended the historical truth of Christ's resurrection.",
    "Richard Hooker": "Richard Hooker (1554–1600), an influential Anglican theologian whose landmark work Of the Laws of Ecclesiastical Polity shaped Anglican theology and ecclesiology.",
    "Thomas Jackson": "Thomas Jackson (1579–1640), an eminent English Arminian theologian, President of Corpus Christi College, Oxford, and Dean of Peterborough, known for his vast theological writings.",
    "George Downham": "George Downham (d. 1634), Bishop of Derry, a Reformed theologian and logician, noted for his defense of the Reformed doctrine of justification.",
    "Theophilus Polwhele": "Theophilus Polwhele (Polwheil) (d. 1689), an English nonconformist minister ejected from Tiverton, Devon, in 1662, who wrote on the Holy Spirit.",
    "Theophilus Polwheil": "Theophilus Polwhele (Polwheil) (d. 1689), an English nonconformist minister ejected from Tiverton, Devon, in 1662, who wrote on the Holy Spirit.",
    "Matthew Sutcliffe": "Matthew Sutcliffe (c. 1550–1629), Dean of Exeter and prominent anti-Catholic polemicist, who founded a college at Chelsea for controversial theology.",

    # Volume 5 Expansion Figures
    "Gaspare Contarini": "Gaspare Contarini (1483–1542), an Italian diplomat, cardinal, and theologian, who sought reconciliation with early Protestants and advocated a moderate view of justification.",
    "Cardinal Contarinus": "Gaspare Contarini (1483–1542), an Italian diplomat, cardinal, and theologian, who sought reconciliation with early Protestants and advocated a moderate view of justification.",
    "Thomas Jacomb": "Thomas Jacomb (1622–1687), an English nonconformist Presbyterian minister ejected in 1662, renowned for his sermons on Romans 8 and defense of Reformed theology.",
    "William Grimshaw": "William Grimshaw of Haworth (1708–1763), an active Anglican clergyman and leader in the 18th-century Methodist revival in England.",
    "William Grimshawe": "William Grimshaw of Haworth (1708–1763), an active Anglican clergyman and leader in the 18th-century Methodist revival in England.",
    "Thomas Hotchkis": "Thomas Hotchkis (17th century), an Anglican minister who wrote treatises opposing Reformed views on justification, imputation, and communion with God.",
    "John Humfrey": "John Humfrey (Humphrey) (1621–1719), an ejected nonconformist minister and writer who advocated pacifism and a middle way on the doctrine of justification.",
    "Samuel Horsley": "Samuel Horsley (1733–1806), Bishop of St Asaph and prominent scientist, who edited Isaac Newton's works and vigorously defended orthodox Trinitarianism against Joseph Priestley.",
    "Thomas Barlow": "Thomas Barlow (1607–1691), Bishop of Lincoln and former tutor of John Owen at Queen's College, Oxford, who remained a lifelong friend and defender of nonconformists.",
    "Joseph Williams": "Joseph Williams of Kidderminster (1692–1755), a pious nonconformist merchant whose published diaries and letters were widely read for spiritual encouragement.",
    "Caspar Ulenberg": "Caspar Ulenberg (Casparus Ulenbergius) (1548–1617), a German Catholic theologian, convert, and Bible translator who wrote polemics against Protestantism.",
    "Casparus Ulenbergius": "Caspar Ulenberg (Casparus Ulenbergius) (1548–1617), a German Catholic theologian, convert, and Bible translator who wrote polemics against Protestantism.",
    "Isaac Chauncey": "Isaac Chauncy (1635–1712), a nonconformist physician and Independent minister in London who succeeded John Owen as pastor of the Mark Lane congregation in 1687.",
    "Albertus Pighius": "Albert Pighius (c. 1490–1542), Dutch Catholic theologian and controversialist, who defended free will and the papacy in debates with John Calvin.",

    # Additional Volume 2 Reformed Theologians & Aliases
    "Paraeus": "David Pareus (Paraeus) (1548–1622), German Reformed Protestant theologian and professor at Heidelberg, known for his biblical commentaries and irenic efforts to unite Lutherans and Calvinists.",
    "Piscator": "Johannes Piscator (1546–1625), German Reformed theologian, Bible translator, and professor at Herborn, known for his extensive commentaries and controversies over the active obedience of Christ in justification.",
    "Voetius": "Gisbertus Voetius (Gisbert Voet) (1589–1676), highly influential Dutch Reformed theologian, Utrecht professor, and Utrecht church founder, who defended strict Reformed orthodoxy at the Synod of Dort.",
    "Placaeus": "Josué de la Place (Joshua Placaeus) (1596–1655), French Reformed theologian and professor at Saumur, whose theory of the mediate imputation of Adam's sin sparked major theological controversy.",
    "Thysius": "Antonius Thysius the Elder (1565–1640), Dutch Reformed theologian and professor of theology at Leiden, who served as a delegate to the Synod of Dort.",
    "Maresius": "Samuel Maresius (Samuel Des Marets) (1599–1673), French-born Reformed theologian and professor at Groningen, known for his dogmatic works and sharp polemics against Socinians and Cartesians.",
    "Essenius": "Andreas Essenius (1618–1689), Dutch Reformed theologian, pastor, and professor of theology at Utrecht, who defended Reformed orthodoxy against Cartesian philosophy and Cocceianism.",
    "Turretinus": "Francis Turretin (François Turretini) (1623–1687), Genevan Reformed Scholastic theologian, whose Institutio Theologiae Elencticae was a landmark defense of orthodox Calvinist theology.",
    "Camero": "John Cameron (c. 1579–1625), a Scottish Reformed theologian who spent much of his life in France, professor at Saumur, founder of the Saumur school of moderate Calvinism.",
    "Rivetus": "André Rivet (1572–1651), French Huguenot theologian and professor of theology at Leiden, known for his polemical treatises and biblical commentaries.",
    "Althingius": "Johann Heinrich Alting (1583–1644), a German Reformed theologian, professor at Heidelberg and Groningen, who represented the Palatinate at the Synod of Dort.",

    # Volume 12 Trinitarian and Anti-Socinian Divines
    "Daniel Waterland": "Daniel Waterland (1683–1740), eminent Anglican theologian and champion of orthodoxy, famous for his extensive defenses of the Nicene doctrine of the Trinity and Christ's divinity against Arianism.",
    "Andrew Fuller": "Andrew Fuller (1754–1815), influential Particular Baptist minister and theologian, who promoted missionary work and defended orthodox Calvinism against Socinian and Sandemanian errors.",
    "William Magee": "William Magee (1766–1831), Archbishop of Dublin and theological writer, renowned for his Discourses and Dissertations on the Scriptural Doctrines of Atonement and Sacrifice defending orthodox views against Unitarianism.",
    "John Pye Smith": "John Pye Smith (1774–1851), English Congregational theologian, academic, and author of The Scripture Testimony to the Messiah, a monumental defense of the deity of Christ against Socinianism.",
    "Ralph Wardlaw": "Ralph Wardlaw (1779–1853), Scottish Congregational minister, theologian, and writer, noted for his Discourses on the Socinian Controversy.",

    # Surnames and new biographical figures mapping (Volume 12 and general)
    "Beza": "Theodore Beza (1519–1605), a French Protestant Christian theologian, reformer, and scholar who succeeded John Calvin as the leader of the Reformed church in Geneva.",
    "Crellius": "Johannes Crellius (John Crell) (1590–1633), a prominent German-Polish Socinian theologian, writer, and rector of the Racovian Academy, known for his biblical commentaries and ethical treatises.",
    "Franken": "Christian Franken (1549–c. 1602), a German writer who was successively a Jesuit, Unitarian, and critic of Socinus, famous for his disputation with Socinus regarding the adoration of Christ.",
    "Alciatus": "Giovanni Paolo Alciati (d. c. 1573), an Italian physician and antitrinitarian who fled to Switzerland and then Poland, joining the early antitrinitarian movement.",
    "Ochinus": "Bernardino Ochino (1487–1564), a famous Italian Capuchin reformer who converted to Protestantism, preached in England and Switzerland, and later published dialogues containing antitrinitarian views.",
    "Bielenscius": "Daniel Bieliński (Daniel Bielenscius) (16th century), a Polish Antitrinitarian leader who initially held radical 'Judaizing' views but later repented and returned to the Reformed faith.",
    "Gitichius": "Michał Gittich (Michael Gitichius) (d. 1654), a Polish Socinian minister and writer who was later excommunicated from the Socinian community for his radical views.",
    "Seidelius": "Martin Seidel (Martin Seidelius) (d. c. 1612), a German antitrinitarian who advocated a form of deism denying the authority of the New Testament and the messiahship of Christ.",
    "Ronembergius": "Simon Ronemberg (Simon Ronembergius), a prominent Polish pharmacist, elder, and patron of the Socinian congregation in Kraków and Raków.",
    "Neuserus": "Adam Neuser (Adam Neuserus) (c. 1530–1576), a German Reformed pastor in Heidelberg who converted to Antitrinitarianism and ultimately fled to the Ottoman Empire, where he converted to Islam.",
    "Lubbertus": "Sibrand Lubbert (Sibrandus Lubbertus) (c. 1555–1625), a Dutch Reformed theologian and professor at Franeker who wrote polemics against Faustus Socinus and Conrad Vorstius.",
    "Wengerscius": "Andreas Węgierski (Adrian Regenvolscius) (1600–1649), a Polish Reformed minister and church historian who documented the history of the Slavic Protestant churches.",
    "Ostorodius": "Christoph Ostorodt (Christophorus Ostorodius) (d. 1611), a German-born Polish Socinian minister and writer, who co-authored a major Socinian catechism.",
    "Voidovius": "Andrzej Wojdowski (Andreas Voidovius) (1565–1622), a Polish Socinian writer and theologian who traveled widely in Western Europe promoting antitrinitarianism.",
    "Blandrata": "Giorgio Biandrata (George Blandrata) (1515–1588), an Italian physician and court theologian in Poland and Transylvania who was a leading organizer of the antitrinitarian churches.",
    "Statorius": "Pierre Statorius (Peter Statorius) (d. 1591), a French-born reformer and grammarian who became a Socinian minister in Poland and wrote the first grammar of the Polish language.",
    "Schlusselburgius": "Conrad Schlüsselburg (Conradus Schlusselburgius) (1543–1619), a German Lutheran theologian, co-author of the Formula of Concord, who wrote extensively against Calvinism and various heresies.",
    "Schlusselburg": "Conrad Schlüsselburg (Conradus Schlusselburgius) (1543–1619), a German Lutheran theologian, co-author of the Formula of Concord, who wrote extensively against Calvinism and various heresies.",
    "Gerlachius": "Stephen Gerlach (Stephanus Gerlachius) (1546–1612), a German Lutheran theologian, preacher, and professor at Tübingen, known for his diary of his travels to Constantinople.",
    "Gerlach": "Stephen Gerlach (Stephanus Gerlachius) (1546–1612), a German Lutheran theologian, preacher, and professor at Tübingen, known for his diary of his travels to Constantinople.",
    "Bull": "George Bull (1634–1710), Bishop of St Davids and eminent Anglican theologian, renowned for his Defensio Fidei Nicaenae defending the Nicene doctrine of the Trinity.",
    "Waterland": "Daniel Waterland (1683–1740), eminent Anglican theologian and champion of orthodoxy, famous for his extensive defenses of the Nicene doctrine of the Trinity and Christ's divinity against Arianism.",
    "Horsley": "Samuel Horsley (1733–1806), Bishop of St Asaph and prominent scientist, who edited Isaac Newton's works and vigorously defended orthodox Trinitarianism against Joseph Priestley.",
    "Magee": "William Magee (1766–1831), Archbishop of Dublin and theological writer, renowned for his Discourses and Dissertations on the Scriptural Doctrines of Atonement and Sacrifice defending orthodox views against Unitarianism.",
    "Pye Smith": "John Pye Smith (1774–1851), English Congregational theologian, academic, and author of The Scripture Testimony to the Messiah, a monumental defense of the deity of Christ against Socinianism.",
    "Wardlaw": "Ralph Wardlaw (1779–1853), Scottish Congregational minister, theologian, and writer, noted for his Discourses on the Socinian Controversy.",
    "Nicolas Estwick": "Nicolas Estwick (c. 1581–1657), English Puritan minister and writer, author of a refutation of John Biddle's anti-Trinitarian tracts.",
    "Poole": "Matthew Poole (1624–1679), English Nonconformist theologian and commentator, famous for his monumental Synopsis Criticorum.",
    "Matthew Poole": "Matthew Poole (1624–1679), English Nonconformist theologian and commentator, famous for his monumental Synopsis Criticorum.",
    "Francis Cheynel": "Francis Cheynell (1608–1665), English Puritan divine and controversialist, noted for his anti-Socinian and anti-Arminian writings.",
    "Francis Cheynell": "Francis Cheynell (1608–1665), English Puritan divine and controversialist, noted for his anti-Socinian and anti-Arminian writings.",
    "Cheynel": "Francis Cheynell (1608–1665), English Puritan divine and controversialist, noted for his anti-Socinian and anti-Arminian writings.",
    "Jerome Moscorovius": "Hieronim Moskorzowski (Jerome Moscorovius) (c. 1560–1625), Polish nobleman and Socinian writer who translated the Racovian Catechism into Latin.",
    "Moscorovius": "Hieronim Moskorzowski (Jerome Moscorovius) (c. 1560–1625), Polish nobleman and Socinian writer who translated the Racovian Catechism into Latin.",
    "George Schomann": "Jerzy Szoman (George Schomann) (1530–1591), Polish antitrinitarian theologian and writer, early compiler of a confession of faith for the Polish Brethren.",
    "Schomann": "Jerzy Szoman (George Schomann) (1530–1591), Polish antitrinitarian theologian and writer, early compiler of a confession of faith for the Polish Brethren.",
    "Christopher Pezold": "Christopher Pezold (Krzysztof Pezold), 17th-century printer and publisher in Amsterdam who printed the 1680 edition of the Racovian Catechism.",
    "Pezold": "Christopher Pezold (Krzysztof Pezold), 17th-century printer and publisher in Amsterdam who printed the 1680 edition of the Racovian Catechism.",
    "Jacques-Bénigne Bossuet": "Jacques-Bénigne Bossuet (1627–1704), French bishop and theologian, famous orator and defender of French Catholicism.",
    "Bossuet": "Jacques-Bénigne Bossuet (1627–1704), French bishop and theologian, famous orator and defender of French Catholicism.",
    "Gilles Ménage": "Gilles Ménage (Aegidius Menagius) (1613–1692), French scholar, philologist, and writer, author of witty epigrams.",
    "Menage": "Gilles Ménage (Aegidius Menagius) (1613–1692), French scholar, philologist, and writer, author of witty epigrams.",
    "Christoph Sandius": "Christoph Sandius (Christopher Sand) (1644–1680), Prussian Socinian historian and writer, author of Bibliotheca Anti-Trinitariorum.",
    "Sandius": "Christoph Sandius (Christopher Sand) (1644–1680), Prussian Socinian historian and writer, author of Bibliotheca Anti-Trinitariorum.",

    # Early Heretics (Gnostics, Monarchians, and Ebionites)
    "Ebion": "Ebion (early 2nd century AD), traditionally regarded as the eponymous founder of the Ebionites, a Jewish-Christian sect that denied the deity and virgin birth of Jesus Christ, viewing him as a mere man.",
    "Cerinthus": "Cerinthus (c. 100 AD), an early Gnostic and docetic heresiarch who taught that the world was created by a lesser demiurge, and that the divine 'Christ' descended upon the human 'Jesus' at his baptism.",
    "Marcus": "Marcus (Marcus the Magician) (2nd century AD), a disciple of Valentinus who combined Gnosticism with magic and Pythagorean numerology, criticized by Irenaeus in Against Heresies.",
    "Basilides": "Basilides (early 2nd century AD), an early Alexandrian Gnostic heresiarch who taught a complex cosmological system of emanations, light, and darkness, and wrote one of the first Gnostic gospels.",
    "Valentinus": "Valentinus (c. 100–160 AD), the most prominent Gnostic theologian and teacher of the 2nd century, who founded the Valentinian school of Gnosticism, teaching a complex hierarchy of divine Aeons.",
    "Calarbasus": "Colorbasus (Calarbasus) (2nd century AD), a Valentinian Gnostic teacher who used numerology and cosmological calculations, refuted by Irenaeus and Epiphanius.",
    "Marcion": "Marcion of Sinope (c. 85–160 AD), an early heresiarch who rejected the Old Testament and the creator God of Judaism (the demiurge), teaching a docetic Christ sent by the supreme God of love.",
    "Photinus": "Photinus of Sirmium (d. 376 AD), a heretical bishop of Sirmium who revived Dynamic Monarchianism, teaching that Christ did not pre-exist his birth but was a mere man who became the Son through moral progression.",
    "Theodotus": "Theodotus of Byzantium (Theodotus the Tanner) (late 2nd century AD), a dynamic monarchianist heretic who taught that Jesus was a mere man who was born of a virgin and received the Christ at his baptism.",

    # Early Heretic Sects / Adjectival Variants
    "Ebionites": "Ebion (early 2nd century AD), traditionally regarded as the eponymous founder of the Ebionites, a Jewish-Christian sect that denied the deity and virgin birth of Jesus Christ, viewing him as a mere man.",
    "Samosatanians": "Paul of Samosata (Paulus Samosatenus) (200–275 AD), Bishop of Antioch, who was deposed for heresy (Adoptionist Monarchianism) for teaching that Jesus was a mere man filled with the Word of God.",
    "Photinians": "Photinus of Sirmium (d. 376 AD), a heretical bishop of Sirmium who revived Dynamic Monarchianism, teaching that Christ did not pre-exist his birth but was a mere man who became the Son through moral progression.",
    "Valentinians": "Valentinus (c. 100–160 AD), the most prominent Gnostic theologian and teacher of the 2nd century, who founded the Valentinian school of Gnosticism, teaching a complex hierarchy of divine Aeons.",
    "Valentinian": "Valentinus (c. 100–160 AD), the most prominent Gnostic theologian and teacher of the 2nd century, who founded the Valentinian school of Gnosticism, teaching a complex hierarchy of divine Aeons.",
    "Marcionites": "Marcion of Sinope (c. 85–160 AD), an early heresiarch who rejected the Old Testament and the creator God of Judaism (the demiurge), teaching a docetic Christ sent by the supreme God of love.",
    "Marcionite": "Marcion of Sinope (c. 85–160 AD), an early heresiarch who rejected the Old Testament and the creator God of Judaism (the demiurge), teaching a docetic Christ sent by the supreme God of love."
}


