# biography_db.py
"""
Central biographical database of key historical, patristic, classical,
and theological figures mentioned or cited in John Owen's works.
Used to automatically inject first-occurrence pop-up footnotes into the text.
"""

BIOGRAPHICAL_DB = {
    # Existing figures from technical_glossary
    "Calvin": "John Calvin (1509–1564), French theologian, pastor, and reformer during the Protestant Reformation, whose systematic theology (Reformed theology) heavily influenced Puritanism.",
    "Cyril": "Cyril of Alexandria (c. 376–444), Patriarch of Alexandria and Doctor of the Church, known for defending orthodox Christology against Nestorius at the Council of Ephesus (431).",
    "Charnock": "Stephen Charnock (1628–1680), English Puritan Presbyterian theologian, celebrated for his classic treatise on the existence and attributes of God.",
    "Augustine": "Augustine of Hippo (354–430), influential Latin church father and bishop whose writings on grace, original sin, the Trinity, and ecclesiology shaped Western Christian theology.",
    "Chrysostom": "John Chrysostom (c. 347–407), Archbishop of Constantinople and Doctor of the Church, famed for his eloquent preaching, biblical homilies, and liturgical revisions.",
    "Athanasius": "Athanasius of Alexandria (c. 296–373), bishop of Alexandria and Doctor of the Church, renowned for defending the deity of Christ and the Trinity against Arianism.",
    "Erasmus": "Desiderius Erasmus of Rotterdam (1466–1536), Dutch Christian humanist and scholar who published the first print Greek New Testament, laying groundwork for Reformation scholarship.",
    "Socinus": "Faustus Socinus (1539–1604), Italian rationalist theologian who denied the Trinity, the pre-existence and deity of Christ, and penal substitutionary atonement.",
    "Bellarmine": "Robert Bellarmine (1542–1621), Italian Jesuit cardinal and theologian, who was the preeminent Roman Catholic apologist of the Counter-Reformation.",
    "Vorstius": "Conrad Vorstius (1569–1622), German-Dutch theologian accused of Socinianism and heterodoxy, whose appointment at Leiden was opposed by King James I.",
    "Ussher": "James Ussher (1581–1656), Archbishop of Armagh and Primate of All Ireland, renowned scholar who formulated the Ussher chronology of biblical history.",
    "Grotius": "Hugo Grotius (1583–1645), Dutch jurist, statesman, and theologian, who advanced the governmental theory of the atonement and pioneered modern international law.",
    "Arminius": "Jacobus Arminius (1560–1609), Dutch theologian whose critique of Reformed views on predestination led to the Remonstrant (Arminian) movement.",

    # Patristic & Classical Authors from patristic_refs
    "Basil": "Basil of Caesarea (c. 330–379), also called Basil the Great, Bishop of Caesarea and Doctor of the Church, who defended Nicene orthodoxy against Arianism and pioneered communal monasticism.",
    "Eusebius": "Eusebius of Caesarea (c. 260–339), Bishop of Caesarea, historian, and exegete, often called the 'Father of Church History' for his landmark work Historia Ecclesiastica.",
    "Ambrose": "Ambrose of Milan (c. 339–397), Bishop of Milan and Doctor of the Church, famed for his ecclesiastical administration, sermons, and role in Augustine's conversion.",
    "Hilary": "Hilary of Poitiers (c. 310–367), Bishop of Poitiers and Doctor of the Church, called the 'Malleus Arianorum' (Hammer of the Arians) for his fierce defense of Nicene Christology.",
    "Jerome": "Jerome (Hieronymus) (c. 347–420), Latin church father and Doctor of the Church, best known for translating the Bible into Latin (the Vulgate) and for his biblical commentaries.",
    "Origen": "Origen of Alexandria (c. 184–253), influential early Christian scholar, theologian, and exegete, known for his allegorical biblical interpretation and vast textual studies like the Hexapla.",
    "Tertullian": "Tertullian (c. 155–220), prolific early Christian author from Carthage, often called the 'Father of Western Theology' for coining the Latin terminology of the Trinity.",
    "Cyprian": "Cyprian of Carthage (c. 200–258), Bishop of Carthage and influential Latin writer, known for his writings on the unity of the Church and his martyrdom under Valerian.",
    "Epiphanius": "Epiphanius of Salamis (c. 315–403), Bishop of Salamis and heresy hunter, whose chief work, the Panarion, lists and refutes eighty heresies from antiquity.",
    "Irenaeus": "Irenaeus of Lyon (c. 130–202), Bishop of Lugdunum (Lyon) and early Christian apologist, whose treatise Adversus Haereses (Against Heresies) systematically refuted Gnosticism.",
    "Prosper": "Prosper of Aquitaine (c. 390–455), Latin Christian writer and disciple of Augustine, who defended the Augustinian doctrine of grace against semi-Pelagianism.",
    "Gregory of Nazianzus": "Gregory of Nazianzus (c. 329–390), Archbishop of Constantinople and theologian, famed for his Five Theological Orations defending the deity of the Son and Holy Spirit.",
    "Gregory of Nyssa": "Gregory of Nyssa (c. 335–395), Bishop of Nyssa and brother of Basil, key theologian of the Trinity who contributed to the Nicene-Constantinopolitan Creed.",
    "Lactantius": "Lactantius (c. 250–325), early Christian author and advisor to Constantine, known as the 'Christian Cicero' for his elegant defense of Christianity in his Divine Institutes.",
    "Theodoret": "Theodoret of Cyrrhus (c. 393–457), influential bishop, theologian, and historian of the school of Antioch, known for his Christological writings and biblical commentaries.",
    "Socrates Scholasticus": "Socrates Scholasticus (c. 380–440), Greek church historian whose Ecclesiastical History covers the history of the early Church from 305 to 439.",
    "Leo the Great": "Leo I (c. 400–461), Pope and Doctor of the Church, whose Tome of Leo defined orthodox Christological doctrine (two natures in one person) for the Council of Chalcedon.",
    "Maximus": "Maximus of Turin (c. 380–420), Bishop of Turin and early Christian writer, known for his numerous short homilies on liturgical, ethical, and biblical topics.",
    "Didymus": "Didymus the Blind (c. 313–398), Alexandrian theologian and head of the Catechetical School of Alexandria, admired for his theological treatises on the Holy Spirit and the Trinity.",
    "Novatian": "Novatian (c. 200–258), Roman theologian, writer, and early antipope, who taught strict discipline regarding the lapsed and wrote the landmark De Trinitate.",
    "Aristotle": "Aristotle (384–322 BC), classical Greek philosopher and polymath, whose works on logic, metaphysics, ethics, and physics profoundly shaped medieval Scholasticism.",
    "Plato": "Plato (c. 428–348 BC), classical Greek philosopher, founder of the Academy, whose theory of Forms and dialogues heavily influenced early Christian theology and Neoplatonism.",
    "Cicero": "Marcus Tullius Cicero (106–43 BC), Roman statesman, orator, and philosopher, whose writings on rhetoric, duty, and politics influenced Western humanist education.",
    "Virgil": "Publius Vergilius Maro (70–19 BC), classical Roman poet, author of the Eclogues, Georgics, and the epic Aeneid, widely read throughout Christian antiquity and the Middle Ages.",
    "Horace": "Quintus Horatius Flaccus (65–8 BC), leading Roman lyric poet of the Augustan era, famed for his Satires, Epistles, and Odes.",
    "Seneca": "Lucius Annaeus Seneca (c. 4 BC–65 AD), Roman Stoic philosopher, statesman, and dramatist, whose moral letters to Lucilius were highly regarded by early Christian writers.",
    "Varro": "Marcus Terentius Varro (116–27 BC), prolific ancient Roman scholar and writer, whose works covered agriculture, language, and Roman antiquities.",
    "Livy": "Titus Livius (Livy) (c. 59 BC–17 AD), Roman historian who wrote Ab Urbe Condita Libri, a monumental history of Rome and its people.",
    "Plutarch": "Plutarch (c. 46–119 AD), Greek philosopher, biographer, and essayist, famed for his Parallel Lives comparing Greek and Roman figures.",
    "Aquinas": "Thomas Aquinas (1225–1274), Italian Dominican friar, Doctor of the Church, and the preeminent Scholastic theologian, whose Summa Theologiae synthesized Aristotelianism and Christian theology.",
    "Petavius": "Denis Pétau (Petavius) (1583–1652), French Jesuit theologian and scholar, whose monumental De Theologicis Dogmatibus pioneered the history of Christian dogma.",
    "Montacutius": "Richard Montague (Montacutius) (1577–1641), controversial Arminian Anglican bishop and scholar, known for his anti-Puritan treatises and patristic studies.",
    "Melchior Cano": "Melchior Cano (1509–1560), Spanish Dominican theologian, bishop, and Scholastic scholar, whose De Locis Theologicis established a methodology for theological authorities.",
    "Sozomen": "Salminius Hermias Sozomen (c. 400–450), Christian historian of Palestine, whose Ecclesiastical History covers the period from Constantine to Theodosius II.",
    "John of Damascus": "John of Damascus (c. 675–749), Syrian monk, priest, and Doctor of the Church, whose De Fide Orthodoxa systematically summarized Eastern patristic theology.",
    "Bernard": "Bernard of Clairvaux (1090–1153), French Cistercian abbot, reformer, and mystic, known for his monastic theology and role in reviving the Cistercian order.",
    "Constantine": "Constantine I (272–337 AD), first Roman emperor to convert to Christianity, who issued the Edict of Milan (313) and convoked the Council of Nicaea (325).",
    "Ephraim": "Ephraim Syrus (Ephrem the Syrian) (c. 306–373), Syriac deacon, hymnwriter, and theologian, renowned for his theological poetry and defenses of the Trinity.",
    "Fulgentius": "Fulgentius of Ruspe (468–533), Bishop of Ruspe in North Africa, a leading defender of Augustinian theology against semi-Pelagianism and Arianism.",
    "Clement of Alexandria": "Clement of Alexandria (c. 150–215), Christian theologian and head of the Catechetical School of Alexandria, who sought to harmonize Greek philosophy with Christian faith.",
    "Theophylact": "Theophylact of Ohrid (c. 1055–1107), Byzantine Archbishop of Ohrid, famed for his clear biblical commentaries which were highly regarded by both Catholic and Protestant reformers.",
    "Cassiodorus": "Marcus Aurelius Cassiodorus (c. 485–585), Roman statesman and writer, who established the Vivarium monastery where monks preserved classical and theological texts.",
    "Theophanes": "Theophanes the Confessor (c. 758–818), Byzantine monk and chronicler, whose Chronicle is a primary historical source for Byzantine history.",
    "Peter Chrysologus": "Peter Chrysologus (c. 380–450), Bishop of Ravenna and Doctor of the Church, famed for his short, eloquent homilies, earning him the name 'Golden-worded' (Chrysologus).",
    "Rufinus": "Rufinus of Aquileia (c. 344–411), Latin monk, historian, and translator, who translated Origen's works and Eusebius's Ecclesiastical History into Latin.",
    "Pliny": "Pliny the Younger (61–c. 113 AD), Roman lawyer and author, whose letters to Trajan contain the earliest non-Christian description of Christian worship.",
    "Ignatius": "Ignatius of Antioch (c. 35–108 AD), Bishop of Antioch, who wrote a series of seven letters on ecclesiology, church order, and theology while en route to his martyrdom in Rome.",
    "Tacitus": "Publius Cornelius Tacitus (c. 56–120 AD), Roman historian and senator, whose Annals and Histories document the reigns of early emperors and contain early references to Christ.",
    "Justin": "Justin (Marcus Junianus Justinus), 2nd or 3rd-century Roman historian who compiled an epitome of the historical works of Pompeius Trogus.",
    "Thucydides": "Thucydides (c. 460–400 BC), Athenian historian and general, whose History of the Peloponnesian War pioneered scientific, evidence-based historical writing.",
    "Herodian": "Herodian of Antioch (c. 170–240 AD), Greek historian who wrote a history of the Roman Empire from the death of Marcus Aurelius to the accession of Gordian III.",
    "Josephus": "Flavius Josephus (37–c. 100 AD), Jewish historian and apologist, whose Jewish Antiquities and The Jewish War are critical sources for first-century Jewish history.",
    "Glassius": "Salomo Glassius (1593–1656), German Lutheran theologian and biblical scholar, whose Philologia Sacra was a classic textbook on biblical hermeneutics and language.",
    "Drusius": "Johannes Drusius (1550–1616), Flemish Protestant divine and distinguished Semitic scholar, known for his studies on biblical antiquities and Hebrew philology.",
    "Volkelius": "Johannes Volkelius (c. 1560–1618), German Socinian theologian and writer, whose De Vera Religione (1630) was a comprehensive systematic theology of Socinianism.",
    "Stapleton": "Thomas Stapleton (1535–1598), English Roman Catholic controversialist and theologian, who defended Catholic authority against Protestant reformers from Louvain.",
    "Mantuanus": "Baptista Mantuanus (1447–1516), Italian Carmelite reformer and humanist poet, whose Latin eclogues were widely used in European school curricula.",
    "Episcopius": "Simon Episcopius (1583–1643), Dutch theologian and professor, who draft the Remonstrance of 1610 and became the principal defender of Arminianism after Arminius.",
    "Sixtinus Amama": "Sixtinus Amama (1593–1629), Dutch Reformed theologian and Semitic linguist, who advocated for the study of biblical languages for ministers.",
    "Xenophon": "Xenophon (c. 430–354 BC), classical Greek historian, philosopher, and student of Socrates, famed for his Anabasis and Cyropaedia.",
    "Dionysius": "Dionysius of Halicarnassus (c. 60–7 BC), Greek historian and teacher of rhetoric, whose Roman Antiquities detailed the early history of Rome.",
    "Rainolds": "John Rainolds (1549–1607), English Puritan scholar and President of Corpus Christi College, Oxford, who initiated the proposal for the King James Bible translation.",
    "Rivet": "André Rivet (1572–1651), French Huguenot theologian and professor of theology at Leiden, known for his polemical treatises and biblical commentaries.",
    "Scultetus": "Abraham Scultetus (1566–1624), German Reformed theologian, professor of theology at Heidelberg, and court preacher to Frederick V.",
    "Dio Cassius": "Dio Cassius (c. 155–235 AD), Roman consul and historian, who wrote a monumental 80-volume history of Rome in Greek.",
    "Hulsius": "Antonius Hulsius (1615–1685), German-Dutch Reformed theologian and Hebrew scholar, who wrote on Semitic languages and defended biblical reliability.",
    "Galatinus": "Petrus Galatinus (1460–1540), Italian Franciscan friar, Jewish convert, and polemicist, whose De Arcanis Catholicae Veritatis defended Christianity using Rabbinic sources.",
    "Martial": "Marcus Valerius Martialis (Martial) (c. 38–104 AD), Roman poet from Hispania, famous for his twelve books of Epigrams satirizing Roman life.",
    "Sarnicki": "Stanisław Sarnicki (1532–1597), Polish Reformed theologian, historian, and military writer, who studied under Calvin and Melanchthon.",
    "Zanchi": "Girolamo Zanchi (1516–1590), Italian Reformed Scholastic theologian, who taught at Strasbourg and Heidelberg, known for his meticulous treatises on God's nature and predestination.",
    "Scribani": "Carolus Scribani (Clarus Bonarus) (1561–1629), Belgian Jesuit theologian, administrator, and writer, known for his polemical and ascetical works.",
    "Mendoza": "Franciscus de Mendoza (1573–1626), Spanish Jesuit theologian, scholar, and professor of Scripture, known for his erudite commentaries on the Books of Kings.",
    "Paterculus": "Velleius Paterculus (c. 19 BC–31 AD), Roman soldier and historian, who wrote an epitome of Roman history from the Trojan War to the death of Livia.",
    "Servius": "Servius Maurus Honoratus, late 4th-century Roman grammarian and commentator, famous for his detailed commentaries on the works of Virgil.",
    "Stobaeus": "Joannes Stobaeus (5th century AD), Greek compiler and anthologist, who collected extracts from over 500 classical writers, preserving many lost works.",
    "Albo": "Joseph Albo (c. 1380–1444), Spanish Jewish rabbi, philosopher, and apologist, famous for his Sefer ha-Ikkarim (Book of Principles) on Jewish dogma.",
    "Raemond": "Florimond de Raemond (c. 1540–1601), French jurist and historian, who wrote a Catholic history of the Reformation defending Catholic tradition.",
    "Connan": "François Connan (1508–1551), French jurist and humanist scholar, who pioneered modern legal theory in his Commentaria Juris Civilis.",
    "Menochius": "Jacopo Menochio (1532–1607), prominent Italian jurist, judge, and legal scholar, famed for his authoritative works on legal presumptions and civil law.",
    "Pighius": "Albert Pighius (c. 1490–1542), Dutch Catholic theologian and controversialist, who defended free will and the papacy in debates with John Calvin.",
    "Cappel": "Louis Cappel (1585–1658), French Huguenot divine, Hebrew scholar, and professor at Saumur, famous for showing the Hebrew vowel points were post-biblical.",
    "Morinus": "Jean Morin (Morinus) (1591–1659), French theologian, oratorian, and biblical scholar, who edited the Paris Polyglot and wrote on the Samaritan Pentateuch.",
    "Isaac": "Johannes Isaac (1515–1597), Jewish convert to Catholicism, grammarian, and professor of Hebrew at Cologne, known for his defenses of Hebrew grammar.",
    "Fuller": "Nicholas Fuller (1557–1626), English Hebraist, philologist, and prebendary of Salisbury, whose Miscellanea Sacra explored biblical antiquities.",
    "Azariah": "Azariah de' Rossi (c. 1511–1578), Italian Jewish physician and scholar, whose Me'or Einayim critically evaluated Jewish history and chronology using classical sources.",
    "Justinian": "Justinian I (482–565 AD), Eastern Roman Emperor famed for reorganizing Roman law in the Corpus Juris Civilis, which shaped subsequent European jurisprudence.",
    "Plotinus": "Plotinus (c. 204–270 AD), Hellenistic philosopher born in Egypt, the founder of Neoplatonism, whose concepts of the 'One' influenced early Christian theology.",

    # New prominent figures detected from scanning volume text
    "Baxter": "Richard Baxter (1615–1691), English Puritan churchman, pastor, and theologian, whose moderate Reformed views (Amyraldianism) and pastoral classic The Reformed Pastor were highly influential.",
    "Justin Martyr": "Justin Martyr (c. 100–165 AD), early Christian apologist, philosopher, and martyr, whose First and Second Apologies defended Christian theology and worship against Roman paganism.",
    "Simon Magus": "Simon Magus (Simon the Sorcerer), a first-century Samaritan magician mentioned in Acts 8:9–24, traditionally identified in patristic literature as the archetype of all heretics.",
    "Biddle": "John Biddle (1615–1662), English schoolmaster and theologian, often called the 'Father of English Unitarianism' for his anti-Trinitarian tracts and teachings.",
    "Arias Montanus": "Benedictus Arias Montanus (1527–1598), Spanish Benedictine orientalist, scholar, and diplomat, who edited the landmark Antwerp Polyglot Bible (1569–1572).",
    "Thomas More": "Thomas More (1478–1535), English humanist scholar, statesman, and Chancellor of England, who opposed the Protestant Reformation and was executed for refusing to acknowledge Henry VIII as Supreme Head of the Church.",
    "Paulus Samosatenus": "Paul of Samosata (Paulus Samosatenus) (200–275 AD), Bishop of Antioch, who was deposed for heresy (Adoptionist Monarchianism) for teaching that Jesus was a mere man filled with the Word of God.",
    "Pontius Pilate": "Pontius Pilate, Roman prefect of Judea (26–36 AD) under Emperor Tiberius, who presided over the trial of Jesus Christ and authorized His crucifixion.",
    "Orme": "William Orme (1787–1830), Scottish Congregational minister and biographer, who wrote the first comprehensive biography of John Owen (Memoirs of the Life, Writings, and Religious Connections of John Owen, D.D.) in 1820.",
    "Hammond": "Henry Hammond (1605–1660), pioneering English Anglican churchman, chaplain to Charles I, and theologian, celebrated for his Paraphrase and Annotations on the New Testament.",
    "Smalcius": "Valentin Schmalz (Valentinus Smalcius) (1572–1622), German-Polish Socinian writer and theologian, who helped draft the Racovian Catechism (1605) and defended anti-Trinitarianism.",
}
