CHUNK_DICT = {
    "Bellarmine, De Laic., cap. 22": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Laicis</i>, cap. 22.",
    "Gregory's Dialogues, lib. 1 cap. 4": "<b>Modern Citation:</b> Gregory the Great, <i>Dialogues</i>, lib. 1, cap. 4.",
    "Vaselius Groningen. De Potestat. Ecclesiastes et Epist. ad Jacob. Hock. Alliacens. in lib. 1:Sentent.": "<b>Modern Citation:</b> Wessel Gansfort, <i>De Potestate Ecclesiastica</i>; and <i>Epistola ad Jacobum Hoeck</i>; Pierre d'Ailly, <i>In Librum Primum Sententiarum</i>.",
    "Austin, in his Confessions, lib. 6 cap. 5, \"Persuasisti mihi, o Domine Deus": "<b>Modern Citation:</b> Augustine, <i>Confessions</i>, lib. 6, cap. 5. \"Persuasisti mihi, o Domine Deus...\"",
    "Baptista Mantuanus, Lib. de Patientia, cap. 32, 33. \"Saepenumero,\" saith he, \"mecum cogitavi,": "<b>Modern Citation:</b> Baptista Mantuanus, <i>De Patientia</i>, cap. 32, 33. \"Saepenumero... mecum cogitavi...\"",
    "Homil. 33, in Act. Apost. cap. 15 Τί οῦν, saith he,  [[BLOCKQUOTE]] ἇν εἴπωμεν π": "<b>Modern Citation:</b> John Chrysostom, <i>Homilies on the Acts of the Apostles</i>, Homily 33, on cap. 15.",
    "Eusebius manifests, lib. 2 cap. 25.": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 2, cap. 25.",
    "Eusebius, Hist. lib. 3 cap. 1": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 3, cap. 1.",
    "Plaut. Epist. 3:4,18.": "<b>Modern Citation:</b> Plautus, <i>Epistles</i>, 3:4, 18.",
    "Ecclesiastical Hierarchies, lib. 1 cap. 4": "<b>Modern Citation:</b> Pseudo-Dionysius the Areopagite, <i>Ecclesiastical Hierarchy</i>, lib. 1, cap. 4.",
    "Bernard, Epist. 42, ad Archiepisc. Senonena": "<b>Modern Citation:</b> Bernard of Clairvaux, <i>Epistola 42, ad Archiepiscopum Senonensem</i>.",
    "Socrat. lib. 1 cap. 28, and cap. 34": "<b>Modern Citation:</b> Socrates Scholasticus, <i>Church History</i>, lib. 1, cap. 28, and cap. 34.",
    "Athan. Apol. 2": "<b>Modern Citation:</b> Athanasius, <i>Apologia Secunda</i>.",
    "Euseb. lib. 10 cap. 5": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 10, cap. 5.",
    "August. Epist. 162, 166, and Advers.  Crescon lib. 3 cap. 17": "<b>Modern Citation:</b> Augustine, <i>Epistolae</i> 162, 166; and <i>Contra Cresconium</i>, lib. 3, cap. 17.",
    "Bellarmine, lib. 5, De Pont, cap. 1": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Romano Pontifice</i>, lib. 5, cap. 1.",
    "Carerius, lib. 1 cap. 9": "<b>Modern Citation:</b> Alexander Carerius, <i>De Potestate Romani Pontificis</i>, lib. 1, cap. 9.",
    "cap. de Major. et Obed.": "<b>Modern Citation:</b> <i>Decretales Gregorii IX</i>, De Majoritate et Obedientia.",
    "De Cleric. lib. 1 cap. 28.": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Clericis</i>, lib. 1, cap. 28.",
    "Beda, lib. 1 cap. 4": "<b>Modern Citation:</b> Bede, <i>Ecclesiastical History of the English People</i>, lib. 1, cap. 4.",
    "Augustin. Lib. de Fid. et Bon. Op. cap. 19": "<b>Modern Citation:</b> Augustine, <i>De Fide et Operibus</i>, cap. 19.",
    "Bed. Hist. lib. 2 cap. 2": "<b>Modern Citation:</b> Bede, <i>Ecclesiastical History of the English People</i>, lib. 2, cap. 2.",
    "De Miss., lib. 1 cap. 2": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Missa</i>, lib. 1, cap. 2.",
    "Azorius, lib. 10 cap. 19": "<b>Modern Citation:</b> Juan Azor, <i>Institutiones Morales</i>, lib. 10, cap. 19.",
    "Irenaeus, lib. 1 cap. 23": "<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, lib. 1, cap. 23.",
    "cap. 24": "<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, lib. 1, cap. 24.",
    "lib. 9 cap. 6": "<b>Modern Citation:</b> [Author], [Work], lib. 9, cap. 6.",
    "Eusebius declares, lib. 7 cap. 18.": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 7, cap. 18.",
    "Seneca decries them, Epist. 33": "<b>Modern Citation:</b> Seneca, <i>Epistulae Morales ad Lucilium</i>, Epistola 33.",
    "Tertullian, Apol., cap. 16, \"Nam quidam somniastis caput asininum e": "<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, cap. 16. \"Nam quidam somniastis caput asininum esse Deum...\"",
    "Homil. ad Pagan.": "<b>Modern Citation:</b> Athanasius, <i>Oratio contra Gentes</i>.",
    "1 Epist. chapter 6": "<b>Modern Citation:</b> 1 Corinthians 6.",
    "Con. Faust lib. 20 cap. 3.": "<b>Modern Citation:</b> Augustine, <i>Contra Faustum Manichaeum</i>, lib. 20, cap. 3.",
    "Basil, in Epist. ad Amphiloch. Con. 44": "<b>Modern Citation:</b> Basil of Caesarea, <i>Epistola 199 (ad Amphilochium)</i>, Canon 44.",
    "Tractat. de Pass. Dom. \"Ego sum vitis,\" cap. 2": "<b>Modern Citation:</b> [Author], <i>Tractatus de Passione Domini</i>, cap. 2.",
    "De Bapt., lib. 1. cap. 51": "<b>Modern Citation:</b> Augustine, <i>De Baptismo contra Donatistas</i>, lib. 1, cap. 51.",
    "Socrat. lib. 5. cap. 8": "<b>Modern Citation:</b> Socrates Scholasticus, <i>Church History</i>, lib. 5, cap. 8.",
    "Eusebius, Eccles. Hist. lib. 4. cap. 22": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 4, cap. 22.",
    "lib. 4. cap. 62.": "<b>Modern Citation:</b> [Author], [Work], lib. 4, cap. 62.",
    "lib. 1. cap. 10.": "<b>Modern Citation:</b> [Author], [Work], lib. 1, cap. 10.",
    "[Adver. Jud., cap. 7.]": "<b>Modern Citation:</b> Tertullian, <i>Adversus Judaeos</i>, cap. 7.",
    "Aug. de Civitate Dei, lib. 10. cap. 59.": "<b>Modern Citation:</b> Augustine, <i>De Civitate Dei</i>, lib. 10, cap. 59.",
    "Post Collationem, cap. 20": "<b>Modern Citation:</b> Augustine, <i>Ad Donatistas post Collationem</i>, cap. 20.",
    "Aristotle, Rhetor. lib. 2. cap. 18": "<b>Modern Citation:</b> Aristotle, <i>Rhetoric</i>, lib. 2, cap. 18.",
    "Epic., cap. 48.": "<b>Modern Citation:</b> Epictetus, <i>Enchiridion</i>, cap. 48.",
    "Epist. Ded.": "<b>Modern Citation:</b> <i>Epistola Dedicatoria</i>.",
    "Socrat., lib. 5. cap. 21.": "<b>Modern Citation:</b> Socrates Scholasticus, <i>Church History</i>, lib. 5, cap. 21.",
    "AElian., lib. 2; Var. Histor., cap. 13.": "<b>Modern Citation:</b> Aelian, <i>Varia Historia</i>, lib. 2, cap. 13.",
    "De Verbo Dei, lib. 1. cap. 1": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Verbo Dei</i>, lib. 1, cap. 1.",
    "Lib. de Confes. Fid.:": "<b>Modern Citation:</b> Constantine the Great, <i>Libellus de Confessione Fidei</i>.",
    "Epist. 80. ad Eustath.": "<b>Modern Citation:</b> Basil of Caesarea, <i>Epistola 80 ad Eustathium</i>.",
    "Comm. in Hagg., cap. 1": "<b>Modern Citation:</b> Jerome, <i>Commentary on Haggai</i>, cap. 1.",
    "Euseb., lib. vii. cap. 27": "<b>Modern Citation:</b> Eusebius, <i>Church History</i>, lib. 7, cap. 27.",
    "Epist. verses 18,19.": "<b>Modern Citation:</b> Philemon 1:18-19.",
    "Bellar., lib 5 cap. l": "<b>Modern Citation:</b> Robert Bellarmine, [Work], lib. 5, cap. 1.",
    "Vasq. in 1,2, quest. 113, disp. 202": "<b>Modern Citation:</b> Gabriel Vasquez, <i>In Primam Secundae Sancti Thomae</i>, quaestio 113, disputatio 202.",
    "Socinus, de Servitor, par. 4 cap. 6": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 4, cap. 6.",
    "Austin, lib. 2 contra Julian., cap. 8.": "<b>Modern Citation:</b> Augustine, <i>Contra Julianum</i>, lib. 2, cap. 8.",
    "Senec. Epist. 31.": "<b>Modern Citation:</b> Seneca, <i>Epistulae Morales ad Lucilium</i>, Epistola 31.",
    "Bellar. de Justificat., lib. 5 cap. 7, prop. 3": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 5, cap. 7, prop. 3.",
    "Epist. ad Diognet.;": "<b>Modern Citation:</b> <i>Epistle to Diognetus</i>.",
    "Orat. 2 in Cant.;": "<b>Modern Citation:</b> Gregory of Nyssa (or Bernard of Clairvaux), <i>Sermones in Cantica Canticorum</i>, Sermo 2.",
    "Enchirid. ad Laurent., cap. 41": "<b>Modern Citation:</b> Augustine, <i>Enchiridion ad Laurentium</i>, cap. 41.",
    "2 Epist. ad Corinth, cap. 5 hom. 11;": "<b>Modern Citation:</b> John Chrysostom, <i>Homilies on 2 Corinthians</i>, Homily 11, on cap. 5.",
    "Bernard also, Epist. 190, ad Innocent:": "<b>Modern Citation:</b> Bernard of Clairvaux, <i>Epistola 190, ad Innocentium</i>.",
    "Epist. an. 1516, hom. 1": "<b>Modern Citation:</b> [Author], <i>Epistola</i> (1516), homily 1.",
    "Taulerus, Meditat. Vitae Christ, cap. 7": "<b>Modern Citation:</b> Johannes Tauler, <i>Meditationes Vitae Christi</i>, cap. 7.",
    "De Servat., par. 4, cap. 4.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 4, cap. 4.",
    "De Justificat., lib. 2 cap. 7": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 2, cap. 7.",
    "De Justif., lib. 2, cap. 10": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 2, cap. 10.",
    "Bernard, Epist. ad Innocent. 190": "<b>Modern Citation:</b> Bernard of Clairvaux, <i>Epistola 190 ad Innocentium</i>.",
    "De Servator., par. 4, cap. 9.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 4, cap. 9.",
    "De Justificat., lib. 2, cap. 1.": "<b>Modern Citation:</b> Andreas Osiander (or Robert Bellarmine), <i>De Justificatione</i>, lib. 2, cap. 1.",
    "1 Epist. 2, 29, and chap. 3, 7": "<b>Modern Citation:</b> 1 John 2:29 and 3:7.",
    "Bellar., lib. 2 cap. 16, and lib 4 cap. 18.": "<b>Modern Citation:</b> Robert Bellarmine, [Work], lib. 2, cap. 16, and lib. 4, cap. 18.",
    "sess. 6 cap. 10.": "<b>Modern Citation:</b> Council of Trent, Session 6, cap. 10.",
    "Vasquez expressly, in 1,2, q. 114, disp. 222, cap. 3": "<b>Modern Citation:</b> Gabriel Vasquez, <i>In Primam Secundae Sancti Thomae</i>, quaestio 114, disputatio 222, cap. 3.",
    "De Justificat., lib. 2 cap. 15": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 2, cap. 15.",
    "Justificat. Paulin, cap. 8": "<b>Modern Citation:</b> [Author], <i>Justificatio Paulina</i>, cap. 8.",
    "Senec. ad Mart.": "<b>Modern Citation:</b> Seneca, <i>Ad Marciam de Consolatione</i>.",
    "Plin., lib. 18 cap. 1": "<b>Modern Citation:</b> Pliny the Elder, <i>Naturalis Historia</i>, lib. 18, cap. 1.",
    "De Amiss. Grat., lib. 4 cap. 10": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Amissione Gratiae et Statu Peccati</i>, lib. 4, cap. 10.",
    "Augustine to the same purpose, Epist. 120, ad Honoratum,": "<b>Modern Citation:</b> Augustine, <i>Epistola 140 ad Honoratum</i> (formerly Epistola 120).",
    "lib. 3 cap. 33.": "<b>Modern Citation:</b> [Author], [Work], lib. 3, cap. 33.",
    "Cyprian, Epist. 62": "<b>Modern Citation:</b> Cyprian, <i>Epistola 62</i>.",
    "Demonstrate.  Evangeli. lib. 10 cap. 1.": "<b>Modern Citation:</b> Eusebius, <i>Demonstratio Evangelica</i>, lib. 10, cap. 1.",
    "Resp. ad cap., Galatians cap. 9.": "<b>Modern Citation:</b> [Author], <i>Responsio ad caput</i>, on Galatians 9.",
    "Bellarmine distinguishes. De Amiss. Grat., lib. 7 cap. 7": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Amissione Gratiae et Statu Peccati</i>, lib. 7, cap. 7.",
    "lib. 8, cap. 3": "<b>Modern Citation:</b> [Author], [Work], lib. 8, cap. 3.",
    "Socinus, De Servatore, lib. 4 cap. 2-4": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, lib. 4, cap. 2-4.",
    "Socinus, De Servatore, lib. 4 cap. 2-5": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, lib. 4, cap. 2-5.",
    "De Amiss. Grat. et Stat. Peccat., lib. 5 cap. 18.": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Amissione Gratiae et Statu Peccati</i>, lib. 5, cap. 18.",
    "Vasquez the Jesuit, in 1, 2, disp. 204, cap. 4": "<b>Modern Citation:</b> Gabriel Vasquez, <i>In Primam Secundae Sancti Thomae</i>, disputatio 204, cap. 4.",
    "Gregory, in Job. 9, lib. 9, cap. 14": "<b>Modern Citation:</b> Gregory the Great, <i>Moralia in Job</i>, on Job 9, lib. 9, cap. 14.",
    "Socinus de Servat., part 3 cap. 5.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 3, cap. 5.",
    "part 2 cap. 22.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 2, cap. 22.",
    "Augustine, lib. de Spiritu et Litera, cap. 8": "<b>Modern Citation:</b> Augustine, <i>De Spiritu et Littera</i>, cap. 8.",
    "Epist. 200": "<b>Modern Citation:</b> Augustine, <i>Epistola 200</i>.",
    "De Servat., part 4. cap. 2.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 4, cap. 2.",
    "De Servatore, lib. 4 cap. 6.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, lib. 4, cap. 6.",
    "Cyrillus Alexandrinus in Joan. lib. 11 cap. 25": "<b>Modern Citation:</b> Cyril of Alexandria, <i>Commentary on John</i>, lib. 11, cap. 25.",
    "Leo, Epist. 12 ad Juvenalem": "<b>Modern Citation:</b> Pope Leo I, <i>Epistola 139 ad Juvenalem</i> (formerly Epistola 12).",
    "Enchirid. ad Laurent., cap. 4.": "<b>Modern Citation:</b> Augustine, <i>Enchiridion ad Laurentium</i>, cap. 4.",
    "lib. 2 cap. 7, De Justificatione": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 2, cap. 7.",
    "lib. 1, De Purgator., cap. 14": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Purgatorio</i>, lib. 1, cap. 14.",
    "De Justif. Habit, cap. 38.": "<b>Modern Citation:</b> [Author], <i>De Justificatione Habituali</i>, cap. 38.",
    "lib. 1 cap. 18, lib. 1 cap. 19, lib. 5 cap. 5, De Justificat.": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 1, cap. 18; lib. 1, cap. 19; lib. 5, cap. 5.",
    "De Servat. par. 4, cap. l": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 4, cap. 1.",
    "De Justificat. lib. 1 cap. 15.": "<b>Modern Citation:</b> Robert Bellarmine, <i>De Justificatione</i>, lib. 1, cap. 15.",
    "Orat. de Har. Resp.,  9.": "<b>Modern Citation:</b> Cicero, <i>De Haruspicum Responsis</i>, 9.",
    "Canus, Loc. Theol., lib. 2 cap. 8": "<b>Modern Citation:</b> Melchior Cano, <i>De Locis Theologicis</i>, lib. 2, cap. 8.",
    "Calv. Instit., lib. 1 cap. 7, sec. 5.": "<b>Modern Citation:</b> John Calvin, <i>Institutes of the Christian Religion</i>, lib. 1, cap. 7, sec. 5.",
    "Strom. 7 cap. 16": "<b>Modern Citation:</b> Clement of Alexandria, <i>Stromata</i>, lib. 7, cap. 16.",
    "Nemesius, De Homin., cap. 2": "<b>Modern Citation:</b> Nemesius of Emesa, <i>De Natura Hominis</i>, cap. 2.",
    "Confess., lib. 11 cap. 3": "<b>Modern Citation:</b> Augustine, <i>Confessions</i>, lib. 11, cap. 3.",
    "De Patient., lib. 3 cap. 2.": "<b>Modern Citation:</b> Baptista Mantuanus, <i>De Patientia</i>, lib. 3, cap. 2.",
    "De Principiis Fidei, controver. 4, lib. 8 cap. 1": "<b>Modern Citation:</b> Thomas Stapleton, <i>De Principiis Fidei Doctrinalibus</i>, controversia 4, lib. 8, cap. 1.",
    "De Grat. et Lib. Arbit., lib. 6 cap. 3": "<b>Modern Citation:</b> Augustine, <i>De Gratia et Libero Arbitrio</i>, lib. 6, cap. 3.",
    "Melchior Canns, Lee. Theol., lib. 2 cap. 8": "<b>Modern Citation:</b> Melchior Cano, <i>De Locis Theologicis</i>, lib. 2, cap. 8.",
    "Calvin, Institut. lib. 1, cap. 7, sect. 5;": "<b>Modern Citation:</b> John Calvin, <i>Institutes of the Christian Religion</i>, lib. 1, cap. 7, sec. 5.",
    "Hieron. Apol. adv.  Rufin.": "<b>Modern Citation:</b> Jerome, <i>Apologia adversus libros Rufini</i>.",
    "Livy, De Bel. Punic., lib. 24 cap. 30": "<b>Modern Citation:</b> Livy, <i>Ab Urbe Condita</i>, lib. 24 (De Bello Punico), cap. 30.",
    "Liv., lib. 10 cap. 23": "<b>Modern Citation:</b> Livy, <i>Ab Urbe Condita</i>, lib. 10, cap. 23.",
    "Cato, De Re Rustica, cap. 13": "<b>Modern Citation:</b> Cato the Elder, <i>De Agri Cultura</i> (De Re Rustica), cap. 13.",
    "Plotinus, Ennead. 6, lib. 9, cap. 10": "<b>Modern Citation:</b> Plotinus, <i>Enneads</i>, Ennead 6, lib. 9, cap. 10.",
    "August. Epist. 121 ad Probam.": "<b>Modern Citation:</b> Augustine, <i>Epistola 130 ad Probam</i> (formerly Epistola 121).",
    "2 Epist. 13:11.": "<b>Modern Citation:</b> 2 Corinthians 13:11.",
    "1 Epist. 2:24": "<b>Modern Citation:</b> 1 Peter 2:24.",
    "2 Epist., chap. [810119] 1:19-21": "<b>Modern Citation:</b> 2 Peter 1:19-21."
}
