CHUNK_DICT = {
    'Ignatius: Epist. ad Philadelph.': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistula ad Philadelphenses</i>',
    '(Tract. 1:)': '(<b>Modern Citation:</b> Augustine, <i>In Evangelium Johannis Tractatus</i>, 1:)',
    'Euseb. Preparat. Evang., lib. 1 cap. 3:': '<b>Modern Citation:</b> Eusebius, <i>Praeparatio Evangelica</i>, 1.3:',
    '(Tract. 124, in Johan.:)': '(<b>Modern Citation:</b> Augustine, <i>In Evangelium Johannis Tractatus</i>, 124:)',
    'Orat. 5 con. Arian., and Epist. ad African.': '<b>Modern Citation:</b> Athanasius, <i>Orationes contra Arianos</i>, 5; <i>Epistula ad Afros Episcopos</i>.',
    'Epist. 78.': '<b>Modern Citation:</b> Basil of Caesarea, <i>Epistulae</i>, 78.',
    'Epist. 71.': '<b>Modern Citation:</b> Basil of Caesarea, <i>Epistulae</i>, 71.',
    'De Trinitate, lib. 5 cap. 8, 9.': '<b>Modern Citation:</b> Augustine, <i>De Trinitate</i>, 5.8-9.',
    'Epist. ad Successum:': '<b>Modern Citation:</b> Cyril of Alexandria, <i>Epistulae ad Successum</i>:',
    'Demonstratio Evang., lib. 5 cap. 2.': '<b>Modern Citation:</b> Eusebius, <i>Demonstratio Evangelica</i>, 5.2.',
    'Peter Diacon., Lib. De Incarnat. et Grat. Christi, ad Fulgentium.': '<b>Modern Citation:</b> Peter the Deacon, <i>De Incarnatione et Gratia Christi ad Fulgentium</i>.',
    '(Orat. 12,)': '(<b>Modern Citation:</b> Gregory Nazianzen, <i>Orationes</i>, 12,)',
    '(Demonst. Evang., lib. 4 cap. 5, etc.:)': '(<b>Modern Citation:</b> Eusebius, <i>Demonstratio Evangelica</i>, 4.5, etc.:)',
    'Augustinus De Fide, ad Peter Diacon., cap. 17;': '<b>Modern Citation:</b> Augustine, <i>De Fide ad Petrum Diaconum</i>, 17;',
    'Justitianus Imperator Epist. ad Hormisdam, Romae Episcop.': '<b>Modern Citation:</b> Justinian I, <i>Epistula ad Hormisdam papam</i>.',
    '(Comment. in Ezekiel, cap. 46:)': '(<b>Modern Citation:</b> Jerome, <i>Commentarii in Ezechielem</i>, 46:)',
    'Cyprian: De Idolorum Vanitate, cap. 3.': '<b>Modern Citation:</b> Cyprian, <i>De Idolorum Vanitate</i>, 3.',
    '(Lib. de Eleemosyn.:)': '(<b>Modern Citation:</b> Cyprian, <i>De Opere et Eleemosynis</i>:)',
    '(Demonstratio Evangelica, lib. 4 cap. 2:)': '(<b>Modern Citation:</b> Eusebius, <i>Demonstratio Evangelica</i>, 4.2:)',
    'De Ecclesiast. Theol. contra Marcell., lib. 2 cap. 17.': '<b>Modern Citation:</b> Eusebius, <i>De Ecclesiastica Theologia contra Marcellum</i>, 2.17.',
    'Irenaeus, "qui nil molitur inepte:" lib. 1 cap. 1.': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 1.1.',
    'Theodoret, lib. 5 cap. 9.': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 5.9.',
    'Ambrose, De Spirit. Sanct., lib. 1 cap. 14.': '<b>Modern Citation:</b> Ambrose, <i>De Spiritu Sancto</i>, 1.14.',
    'Gregor. Nazianzen, Orat. 40.': '<b>Modern Citation:</b> Gregory Nazianzen, <i>Orationes</i>, 40.',
    'Enchirid., cap. 38.': '<b>Modern Citation:</b> Augustine, <i>Enchiridion</i>, 38.',
    'Cyril. Alex. De Recta Fide, cap. 32.': '<b>Modern Citation:</b> Cyril of Alexandria, <i>De Recta Fide</i>, 32.',
    'August. Lib. con. Serm. Arian, cap. 35,': '<b>Modern Citation:</b> Augustine, <i>Contra Sermonem Arianorum</i>, 35,',
    'Epist. 66 ad Maximum.': '<b>Modern Citation:</b> Augustine, <i>Epistulae</i>, 66 (ad Maximum).',
    'Petrus Galatinus, lib. 3 cap. 4;': '<b>Modern Citation:</b> Petrus Galatinus, <i>De Arcanis Catholicae Veritatis</i>, 3.4;',
    'Irenaeus, lib. 3, cap. 20, 21;': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.20-21;',
    'Eusebius, Demonst. Evangel., lib. 4 cap. 1-4, etc.;': '<b>Modern Citation:</b> Eusebius, <i>Demonstratio Evangelica</i>, 4.1-4, etc.;',
    'Cyril. Alexand., lib. 5 cap. 6,': '<b>Modern Citation:</b> Cyril of Alexandria, <i>Contra Julianum</i>, 5.6,',
    'lib. 1. De Fide ad Regin.;': '<b>Modern Citation:</b> Cyril of Alexandria, <i>De Recta Fide ad Reginas</i>, 1;',
    'Chrysostom, Homil. 10 in Johan.,': '<b>Modern Citation:</b> John Chrysostom, <i>Homiliae in Joannem</i>, 10,',
    'et in cap. 8, ad Romans Serm. 18;': '<b>Modern Citation:</b> John Chrysostom, <i>Homiliae in Epistolam ad Romanos</i>, 18;',
    'Augustine, De Trinit., lib. 13 cap. 13-20;': '<b>Modern Citation:</b> Augustine, <i>De Trinitate</i>, 13.13-20;',
    'Leo, Epist. 13, 18,': '<b>Modern Citation:</b> Leo the Great, <i>Epistulae</i>, 13, 18,',
    'Sermo. De Nativit. 1, 4, 10;': '<b>Modern Citation:</b> Leo the Great, <i>Sermones de Nativitate</i>, 1, 4, 10;',
    'Basil., in Psalm 48;': '<b>Modern Citation:</b> Basil of Caesarea, <i>Homiliae in Psalmos</i>, 48;',
    'Cyril. Hierosol, Cateches. 12;': '<b>Modern Citation:</b> Cyril of Jerusalem, <i>Catecheses</i>, 12;',
    'Gregor. Nazianzen, Orat. 2, 38;': '<b>Modern Citation:</b> Gregory Nazianzen, <i>Orationes</i>, 2, 38;',
    'Gregor. Nyssen., Tractat. de Catechis., cap. 15;': '<b>Modern Citation:</b> Gregory of Nyssa, <i>Oratio Catechetica Magna</i>, 15;',
    'Ambros., lib. 2 de Fide ad Gratianum, cap. 3;': '<b>Modern Citation:</b> Ambrose, <i>De Fide ad Gratianum Augustum</i>, 2.3;',
    'Justin Martyr, Dialog. cum Tryphone;': '<b>Modern Citation:</b> Justin Martyr, <i>Dialogus cum Tryphone</i>;',
    'Epiphanius, in Ancorato;': '<b>Modern Citation:</b> Epiphanius, <i>Ancoratus</i>;',
    'Damascen., lib. 3, De Fide, cap. 15, 19;': '<b>Modern Citation:</b> John of Damascus, <i>De Fide Orthodoxa</i>, 3.15, 19;',
    'Anselm., quod Deus Homo, lib. duo.': '<b>Modern Citation:</b> Anselm, <i>Cur Deus Homo</i>, 1-2.',
    '(lib. 3 cap. 20,)': '(<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.20,)',
    '(lib. 5 cap. 1:)': '(<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 5.1:)',
    '(lib. 5 cap. 14:)': '(<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 5.14:)',
    '(Lib. de Fide, ad Petrum Diaconum:)': '(<b>Modern Citation:</b> Augustine, <i>De Fide ad Petrum Diaconum</i>:)',
    '(lib. 3 cap. 20:)': '(<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.20:)',
    '(Lib. de Definitionibus Orthodoxae Fidei sive de Ecclesiastica Dogmatibus, cap. 2:)': '(<b>Modern Citation:</b> Gennadius of Massilia, <i>De Ecclesiasticis Dogmatibus</i>, 2:)',
    '(Enchirid. ad Laurent., cap. 99:)': '(<b>Modern Citation:</b> Augustine, <i>Enchiridion ad Laurentium</i>, 99:)',
    'Epist. 66 ad Pammach., cap. 10.': '<b>Modern Citation:</b> Jerome, <i>Epistulae</i>, 66 (ad Pammachium), 10.',
    'De Praedest. Sanct., cap. xv.': '<b>Modern Citation:</b> Augustine, <i>De Praedestinatione Sanctorum</i>, 15.',
    'De Trin., lib. 1 cap. 10.': '<b>Modern Citation:</b> Augustine, <i>De Trinitate</i>, 1.10.',
    'Aesch. apud Justin., Apol.  2.': '<b>Modern Citation:</b> Justin Martyr, <i>Apologia Secunda</i>.',
    'August, lib. i. de Trinit. cap. 6': '<b>Modern Citation:</b> Augustine, <i>De Trinitate</i>, 1.6',
    'Clem. Epist. ad Corinth.': '<b>Modern Citation:</b> Clement of Rome, <i>Epistula ad Corinthios</i>.',
    'Tertullian, Apol., cap. v.,': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 5,',
    'Theodoret, Ecclesiastes Hist., lib. 4, cap. 19.': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 4.19.',
    'Socrates Ecclesiastes Hist., lib. 3. cap. 25.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 3.25.',
    'Sozom. Ecclesiastes Hist., lib. vii.. cap. 1.': '<b>Modern Citation:</b> Sozomen, <i>Historia Ecclesiastica</i>, 7.1.',
    'Iren., lib. iii. cap. 3;': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.3;',
    'Euseb. Ecclesiastes Hist., lib. iii. cap. 28.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 3.28.',
    'Euseb., lib. iv. cap.  14.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.14.',
    'lib. iii. cap. 3.': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.3.',
    'Epist. iii. ad Cornel;': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 3 (ad Cornelium);',
    'Ignatius, Epist. ad Philad.;': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistula ad Philadelphenses</i>;',
    'Apol., cap. xxiv.': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 24.',
    'Apol., cap. il.': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 2.',
    'Gregory of Rome, lib. ii. Epist. lii.,': '<b>Modern Citation:</b> Gregory the Great, <i>Epistulae</i>, 2.52,',
    'Euseb., Ecclesiastes Hist., lib. x. cap. 5.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 10.5.',
    'Socrat. Hist., lib. i. cap. 34.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 1.34.',
    'Rufin. Ecclesiastes Hist., lib. i. cap.  11.': '<b>Modern Citation:</b> Rufinus, <i>Historia Ecclesiastica</i>, 1.11.',
    'Rufin., lib. i. cap. 15, 16, etc.': '<b>Modern Citation:</b> Rufinus, <i>Historia Ecclesiastica</i>, 1.15-16, etc.',
    'Leo, Epist. 75:1, etc.': '<b>Modern Citation:</b> Leo the Great, <i>Epistulae</i>, 75.1, etc.',
    'Eusebius, Ecclesiastes Hist., lib. iii. cap. 33,': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 3.33,',
    'Apol cap. ii.': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 2.',
    'Euseb., lib. vii. cap. 1.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.1.',
    'Euseb., lib. vii. cap. 13.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.13.',
    'Dionys. apud Euseb., lib. vii. cap. 21.': '<b>Modern Citation:</b> Dionysius of Alexandria, quoted in Eusebius, <i>Historia Ecclesiastica</i>, 7.21.',
    'Tertul. Apol. et ad Scap.;': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i> and <i>Ad Scapulam</i>;',
    'Euseb. Ecclesiastes Hist., lib. vii. cap. 21;': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.21;',
    'August. de Civit. Dei, lib. xviii. cap. 52;': '<b>Modern Citation:</b> Augustine, <i>De Civitate Dei</i>, 18.52;',
    'Council of Chalcedon, cap. vi.,': '<b>Modern Citation:</b> Council of Chalcedon, Canon 6,',
    'Socrat. Ecclesiastes Hist., lib. vi. cap. 20.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 6.20.',
    'Euseb. de Vita Constant., lib. iv. cap. 23, 24;': '<b>Modern Citation:</b> Eusebius, <i>De Vita Constantini</i>, 4.23-24;',
    'lib. iii. cap. 52.': '<b>Modern Citation:</b> Eusebius, <i>De Vita Constantini</i>, 3.52.',
    'Socrat. Ecclesiastes Hist., lib. v. cap. 16.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 5.16.',
    'Theod. Ecclesiastes Hist., lib. v. cap. 38.': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 5.38.',
    'Socrates, lib. 1 cap. 7.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 1.7.',
    'Eusebius, lib. 3 cap. 32.': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 3.32.',
    'Irenaeus, lib. i.;': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 1;',
    'Tertullian, Praeserip. ad Haeret. cap. 49;': '<b>Modern Citation:</b> Tertullian, <i>De Praescriptione Haereticorum</i>, 49;',
    'Philastrius, in his catalogue of heretics;': '<b>Modern Citation:</b> Philastrius, <i>Diversarum Hereseon Liber</i>;',
    'Hist. Ecclesiastes lib. 5 cap. ult.,': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.28 [ult.],',
    'Euseb. Hist. Ecclesiastes lib. 7 cap. 29, 30': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.29-30',
    'Hilary, De Synodis;': '<b>Modern Citation:</b> Hilary of Poitiers, <i>De Synodis</i>;',
    'Socrat. Ecclesiastes Hist. lib. 2 cap. 24, 25.': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 2.24-25.',
    'tom. 1:lib. 3, Haer. 70;': '<b>Modern Citation:</b> Epiphanius, <i>Panarion</i>, 3, Haer. 70;',
    'Theodoret, Lib. 4 Ecclesiastes Hist., cap. 10,': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 4.10,',
    'De Haer. cap. 1.': '<b>Modern Citation:</b> Augustine, <i>De Haeresibus</i>, 1.',
    'Cyprian adver. Judaeos, lib. 2 cap. 6,': '<b>Modern Citation:</b> Cyprian, <i>Adversus Judaeos</i>, 2.6,',
    'Hilary ad Psalm 12,': '<b>Modern Citation:</b> Hilary of Poitiers, <i>Tractatus super Psalmos</i>, 12,',
    '1 in Johan. Cap. 11;': '<b>Modern Citation:</b> <i>In Evangelium Johannis</i>, 11;',
    'Rainold. de Idol., lib. ii. cap. 1, sect.  1.': '<b>Modern Citation:</b> John Rainolds, <i>De Romanae Ecclesiae Idolatria</i>, 2.1.1.',
    'Bell, de Ecclea Triumph, lib. ii. cap. 24;': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Ecclesia Triumphante</i>, 2.24;',
    'Greg. de Valen. de Idol, lib. i. cap. 1 ;': '<b>Modern Citation:</b> Gregory of Valencia, <i>De Idolatria</i>, 1.1;',
    'Lib. de Laicis, cap. 21.': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Laicis</i>, 21.',
    'Tacitus, Hist., lib. v. cap. 1,': '<b>Modern Citation:</b> Tacitus, <i>Historiae</i>, 5.1,',
    'De Laic, cap. xxii.': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Laicis</i>, 22.',
    'De Laic, cap. xxi.': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Laicis</i>, 21.',
    'Eutrop., lib. viii.': '<b>Modern Citation:</b> Eutropius, <i>Breviarium Historiae Romanae</i>, 8.',
    'Whit., Con. 4 de Romans Pont. qu. 1, cap. 1, sect.  2.': '<b>Modern Citation:</b> William Whitaker, <i>Controversia 4 de Romano Pontifice</i>, q. 1, c. 1, sect. 2.',
    'Con. 4 de Romans Pont. qu. 1, cap. 1, sect. 19, pp. 48 et  50.': '<b>Modern Citation:</b> William Whitaker, <i>Controversia 4 de Romano Pontifice</i>, q. 1, c. 1, sect. 19, pp. 48-50.',
    'lib. 27 cap. 6.': '<b>Modern Citation:</b> Ammianus Marcellinus, <i>Res Gestae</i>, 27.6.',
    'Possevine the Jesuit, in Atheis, sui saeculi, cap. 13 fol. 15.': '<b>Modern Citation:</b> Antonio Possevino, <i>De Atheismis huius saeculi</i>, 13, fol. 15.',
    'cap. 14 p. 366.': '<b>Modern Citation:</b> Antonio Possevino, <i>De Atheismis huius saeculi</i>, 14, p. 366.',
    'Zanchius, at large, "De Tribus Elohim, lib. 6 cap. ii., et deinceps;"': '<b>Modern Citation:</b> Girolamo Zanchi, <i>De Tribus Elohim</i>, 6.2ff.',
    'lib. 3 Amphitrial. Honor. lib. 3 cap. ult. ad Divinam Hallensem et Puerum Jesum,': '<b>Modern Citation:</b> Carolus Scribanius, <i>Amphitheatrum Honoris</i>, 3.ult.',
    'Paterc. Hist. Romans lib. 1 cap. 17.': '<b>Modern Citation:</b> Velleius Paterculus, <i>Historia Romana</i>, 1.17.',
    'lib. 1:cap. 2.);': '<b>Modern Citation:</b> <i>Work</i>, 1.2);',
    'Alcinous, de Doctrina Platon. cap. 10': '<b>Modern Citation:</b> Alcinous, <i>Epitome Doctrinae Platonicae</i>, 10',
    'Socinus pleads, Praelect. Theol. cap. 8;': '<b>Modern Citation:</b> Faustus Socinus, <i>Praelectiones Theologicae</i>, 8;',
    'Volkelius, lib. 5 cap. 11 p. 468;': '<b>Modern Citation:</b> Johannes Volkelius, <i>De Vera Religione</i>, 5.11, p. 468;',
    'Smiglecius, cap. 17, 18,': '<b>Modern Citation:</b> Marcin Śmiglecki, <i>Nova Monstra Novi Arianismi</i>, 17-18,',
    'cap. 18, p. 156,': '<b>Modern Citation:</b> Marcin Śmiglecki, <i>Nova Monstra Novi Arianismi</i>, 18, p. 156,',
    'cap. 17 p. 150.': '<b>Modern Citation:</b> Marcin Śmiglecki, <i>Nova Monstra Novi Arianismi</i>, 17, p. 150.',
    'cap. 18, p. 158.': '<b>Modern Citation:</b> Marcin Śmiglecki, <i>Nova Monstra Novi Arianismi</i>, 18, p. 158.',
    'Smalcius, De Vera Divinit. Jes. Christ, cap. 7, etc.;': '<b>Modern Citation:</b> Valentin Schmalz, <i>De Vera Divinitate Jesu Christi</i>, 7, etc.;',
    'Socin. Disput. cum Erasmo Johan. Rationu': '<b>Modern Citation:</b> Faustus Socinus, <i>Disputatio cum Erasmo Johannis</i>.',
    'Volkel.  De Vera Relig. lib. 5 cap. 10-12.;': '<b>Modern Citation:</b> Johannes Volkelius, <i>De Vera Religione</i>, 5.10-12;',
    'Jonas Schlicht. ad Meisner., pp. 192, 193': '<b>Modern Citation:</b> Jonas Schlichting, <i>Ad Balthasarem Meisnerum</i>, pp. 192-193.',
    'Apology for the Remonstrants, cap. 2 sect.  2.': '<b>Modern Citation:</b> Simon Episcopius, <i>Apologia pro Confessione Remonstrantium</i>, 2.2.',
    'Socinus against Weik, cap. 7 p. 424;': '<b>Modern Citation:</b> Faustus Socinus, <i>Responsio ad Vujekum</i>, 7, p. 424;',
    'Smalcius against Smiglecius, cap. 26;': '<b>Modern Citation:</b> Valentin Schmalz, <i>Refutatio Smiglecii</i>, 26;',
    'Ostorod. in Titus cap. 7,': '<b>Modern Citation:</b> Christoph Ostorodt, <i>Unterricht</i>, 7,',
    'Joseph de Voysin, Pug. Fid, par. 3, dist. 1, cap. 4.': '<b>Modern Citation:</b> Joseph de Voisin, <i>Pugio Fidei</i>, 3.1.4.',
    'Zanchius answers, "De Tribus Elohim," lib. 3 cap. 6 p. 456.': '<b>Modern Citation:</b> Girolamo Zanchi, <i>De Tribus Elohim</i>, 3.6, p. 456.',
    '(Smalc. de Divin. Christi, cap. 16),': '(<b>Modern Citation:</b> Valentin Schmalz, <i>De Vera Divinitate Jesu Christi</i>, 16),',
    'Gomarus, Anal. Epist. Paul. ad Phil cap. 2;': '<b>Modern Citation:</b> Franciscus Gomarus, <i>Analysis Epistolae Pauli ad Philippenses</i>, 2;',
    'Rabbi Joseph Albo, Orat. 1 cap. i.,': '<b>Modern Citation:</b> Joseph Albo, <i>Sefer HaIkkarim</i>, 1.1,'
}
