CHUNK_DICT = {
    'De Spiritu Sancto, lib. 2 cap. 6': '<b>Modern Citation:</b> Basil the Great, <i>De Spiritu Sancto</i>, 2.6.',
    'Concil. Sardicen. in Socrat. lib. 2 cap. 20': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Church History</i>, 2.20.',
    'Maimonides, ("More Nebuch.," page 2, cap. 35.,)': '<b>Modern Citation:</b> Moses Maimonides, <i>Guide for the Perplexed</i>, Part 2, 35.',
    'Sirachides, cap. 45., 46.': '<b>Modern Citation:</b> Ben Sira, <i>Ecclesiasticus</i>, 45-46.',
    'Hieronym. Comment. in Epist. ad Galatians cap. 5.': '<b>Modern Citation:</b> Jerome, <i>Commentary on the Epistle to the Galatians</i>, 5.',
    'Diospolitan synod, that is at Lydda in Palestine, cap. 6.': '<b>Modern Citation:</b> Synod of Diospolis, canon 6.',
    'Austin, cont. Duas Epistol. Pelag. lib. 1. cap. 19: "Trahitur [homo] miris modis ut velit, ab ill': '<b>Modern Citation:</b> Augustine, <i>Against Two Letters of the Pelagians</i>, 1.19.',
    'Confess. lib. 4. cap. 1; — "Let arrogant men deride or scorn me, who we': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 4.1.',
    'Confess. lib. 1. cap. 6,  [[BLOCKQUOTE]] "Paulatim sentiebam ubi essem,': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.6.',
    'cap. 7:  [[BLOCKQUOTE]] "An pro tempore illa bona eran': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.7.',
    'lib. 1. cap. 19.  This is not innocency; it is not so. The sam': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.19.',
    'lib. 1. cap. 19;  — "I saw not (O God) into what a gulf of fil': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.19.',
    'lib. 1. cap. 19.  He sometimes stole from his parents, either ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.19.',
    'lib. 2. cap. 1-3.': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 2.1-3.',
    'cap. 3;  — "I declare these things, O my God, not unto': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 2.3.',
    'Confess. lib. 2. cap. 6.': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 2.6.',
    'Confess. lib. 2. cap. 7:  [[BLOCKQUOTE]] "Diligam te, Domine, et gratia': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 2.7.',
    'lib. 1. cap. 9. And hereunto he adds some general instruction ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.9.',
    'cap. 11. And from the same principles, when he was a l': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.11.',
    'cap. 11.  Such affections and occasional actings of so': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 1.11.',
    'lib. 2. cap. 3; such were those which he had in sicknesses of ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 2.3.',
    'lib. 4. cap. 5-7. And in all the several warnings he had from ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 4.5-7.',
    'Confess. lib. 5. cap. 7-9, etc.  [[BLOCKQUOTE]] "Tu spes mea [et portio': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 5.7-9.',
    'cap. 8;  — "Thou who art my hope [and my portion] in t': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 5.8.',
    'lib. 8. cap. 5:  [[BLOCKQUOTE]] "Suspirabam ligatus non ferro ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.5.',
    'Lib. 8. cap. 7:  [[BLOCKQUOTE]] "Narrabat hoc Pontitia': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.7.',
    'Lib. 8. cap. 5:  [[BLOCKQUOTE]] "Voluntas nova quae mi': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.5.',
    'cap. 9-11, delivering those things which more or less ': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.9-11.',
    'lib. 8. cap. 12;  — "Having read these verses, I would read no': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.12.',
    'lib. 8. cap. 2.': '<b>Modern Citation:</b> Augustine, <i>Confessions</i>, 8.2.',
    'Crell. de Spir. Sanc., cap. 5.': '<b>Modern Citation:</b> Johannes Crellius, <i>De Spiritu Sancto</i>, 5.',
    'De Ecclesiastes lib. 3 cap. 2.': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Ecclesia militante</i>, 3.2.',
    'Bellarmine, De Ecclesiastes lib. 3 cap. 2,': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Ecclesia militante</i>, 3.2.',
    'Demosthenes, Orat. De Corona,': '<b>Modern Citation:</b> Demosthenes, <i>On the Crown</i>.',
    'Thucyd. lib. 3 cap. 49 Καὶ ἐγένοντο ἐν τῇ χειροτονίᾳ ἀγχώμαλοι? ἐκράτ': '<b>Modern Citation:</b> Thucydides, <i>History of the Peloponnesian War</i>, 3.49.',
    'Just., lib. 1 cap. 1.': '<b>Modern Citation:</b> Justin, <i>Epitome of the Philippic History of Pompeius Trogus</i>, 1.1.',
    'CLEMENS, Epist. ad Corinth.,': '<b>Modern Citation:</b> Clement of Rome, <i>First Epistle to the Corinthians</i>.',
    'IGNATIUS, Epist. ad Philadelph., cap. 10, Πρέπον ἐστὶν ὑμῖν, ὡς ἐκ': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistle to the Philadelphians</i>, 10.',
    'TERTULLIAN, Apol., "Praesident probati quique seniores, honorem ist': '<b>Modern Citation:</b> Tertullian, <i>Apology</i>, 39.',
    'Epist. 67, unto the elders and people of some churches i': '<b>Modern Citation:</b> Cyprian, <i>Epistle 67</i>.',
    'Epist. Conc. Ephesians 1, ad Synod. in Pamphyl.': '<b>Modern Citation:</b> Council of Ephesus, <i>Epistle 1, to the Synod in Pamphylia</i>.',
    'Orat. 52, et Vit. Greg.  Nazian.': '<b>Modern Citation:</b> Gregory Nazianzen, <i>Oration 52</i>, and <i>Life of Gregory Nazianzen</i>.',
    'Herodian, lib. 2, cap. 28, Φιλέορτοι δὲ φύσει Σύροι? ῶν μάλιστα οἱ τὴν Α': '<b>Modern Citation:</b> Herodian, <i>History of the Empire</i>, 2.28.',
    'Apol. cap. 39.': '<b>Modern Citation:</b> Tertullian, <i>Apology</i>, 39.',
    'De Coelest, Hierarch. lib. 6, cap. 1.': '<b>Modern Citation:</b> Pseudo-Dionysius the Areopagite, <i>De Coelesti Hierarchia</i>, 6.1.',
    'De Concil. lib. 1, cap. 3,': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Conciliis</i>, 1.3.',
    'Adversus Haereses, lib. 2, cap. 22, sect. 4: "Magister ergo existens, magistri qu': '<b>Modern Citation:</b> Irenaeus, <i>Against Heresies</i>, 2.22.4.',
    'Lib. 1: cap. 18: Οσοι γάρ εἰσι ταύτης τῆς γνώμης μυστα': '<b>Modern Citation:</b> Irenaeus, <i>Against Heresies</i>, 1.18.',
    'Irenaeus, lib. 1, cap. 18,': '<b>Modern Citation:</b> Irenaeus, <i>Against Heresies</i>, 1.18.',
    'Exercit. 1, cap. 1, p. 11,': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, 1.1.',
    '(Exerc. 1, cap. 2.)': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, 1.2.',
    '(Epist. 2:41),': '<b>Modern Citation:</b> Joseph Justus Scaliger, <i>Epistle 241</i>.',
    '(lib. de Auth. Scripturae, cap. 5.)': '<b>Modern Citation:</b> Johannes Cochlaeus, <i>De Authoritate Sacrae Scripturae</i>, 5.',
    '(Isag. ad Scrip. 1, cap. 8.)': '<b>Modern Citation:</b> Author, <i>Isagoge ad Scripturam</i>, 1.8.',
    '(Crit. Sacr. lib. 6, cap. 10): "Planum est omnem quae hodie est in terrarum': '<b>Modern Citation:</b> Ludovicus Cappellus, <i>Critica Sacra</i>, 6.10.',
    '(De Heb. et Graec. Tex. Sincerit. Exercit., 1, cap. 1, p. 5)," It is a jocular thing that the heretic': '<b>Modern Citation:</b> Author, <i>De Hebraici et Graeci Textus Sinceritate Exercitationes</i>, 1.1, p. 5.',
    '(Apol., cap. 5:) "Facit et hoc ad causam nostram, quod a': '<b>Modern Citation:</b> Tertullian, <i>Apology</i>, 5.',
    'Josephus, De Bell. Jud. lib. 7, cap. 24.': '<b>Modern Citation:</b> Flavius Josephus, <i>The Jewish War</i>, 7.24.',
    'Rabbi Moses, Tractat. de Libro Legis. cap. 10. One of them is, אות אחת שׁחסר אפילו, "If but ': '<b>Modern Citation:</b> Moses Maimonides, <i>Mishneh Torah, Hilchot Sefer Torah</i>, 10.',
    'Exercit. lib. 1, cap. 3, p. 15.': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, 1.3, p. 15.',
    'Fuller, Miscellan. lib. 3 cap. 13.': '<b>Modern Citation:</b> Nicholas Fuller, <i>Miscellanea Theologica</i>, 3.13.',
    'Bell. De Verbo Dei, lib. 2, cap. 2,': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Verbo Dei</i>, 2.2.',
    'Cevallerlus goes further: Rudiment. Ling. Heb. cap. 4, "Quod superest de vocalium et centuum antiquit': '<b>Modern Citation:</b> Antoine Rodolphe Chevallier, <i>Rudimenta Hebraicae Linguae</i>, 4.',
    'De Verb. Dei, lib. 2, cap. 2, "Hisce duabus sententiis refutatis, restat ter': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Verbo Dei</i>, 2.2.',
    'Exercit. lib. 1 exer. 1 cap. 2.': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, lib. 1, exer. 1, cap. 2.',
    'Exer. 2 cap. 3, par, poster.;': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, exer. 2, cap. 3.',
    'p. p. 5, cap. 3.': '<b>Modern Citation:</b> Johannes Morinus, <i>Exercitationes Biblicae</i>, pars 2?, cap. 3.',
    'Apol. 2 ad Anton. Pium., Καὶ γὰρ ἐν τῷ νῦν γεγενημένῳ Ι': '<b>Modern Citation:</b> Justin Martyr, <i>Second Apology</i>.',
    'Lightfoot, Chorograph, cap. 81, p. 144.': '<b>Modern Citation:</b> John Lightfoot, <i>Chorographical Century</i>, 81, p. 144.',
    'Galatinus, Arcan. Relig.  Cathol. lib. 1 cap. 7; and Reuchlinnus Cabal lib. 1 p. 636; Guliel.  ': '<b>Modern Citation:</b> Pietro Galatino, <i>De Arcanis Catholicae Veritatis</i>, 1.7; Johann Reuchlin, <i>De Arte Cabalistica</i>, 1, p. 636.',
    'Tacit. Annal. lib. 15 cap. 44.': '<b>Modern Citation:</b> Tacitus, <i>Annals</i>, 15.44.',
    'Lib. Sanhedrim,': '<b>Modern Citation:</b> <i>Babylonian Talmud, Tractate Sanhedrin</i>.',
    'cap. 81 p. 146: "Sunt qui punctata Biblia credunt a sa': '<b>Modern Citation:</b> John Lightfoot, <i>Chorographical Century</i>, 81, p. 146.',
    'R. Azarias at large, Imre Binah. cap. 59.': '<b>Modern Citation:</b> Azariah dei Rossi, <i>Me\'or Einayim, Imre Binah</i>, 59.',
    'Josephus, Antiq. lib. 11 cap. 8.': '<b>Modern Citation:</b> Flavius Josephus, <i>Jewish Antiquities</i>, 11.8.',
    'Joseph Antiq. lib. 13 cap. 10.': '<b>Modern Citation:</b> Flavius Josephus, <i>Jewish Antiquities</i>, 13.10.',
    'R. Azarias, lib. Imre Binah. cap. 59.': '<b>Modern Citation:</b> Azariah dei Rossi, <i>Me\'or Einayim, Imre Binah</i>, 59.',
    'Buxtorfius, De Punct. Antiq. par. 1 cap. 3.': '<b>Modern Citation:</b> Johannes Buxtorf II, <i>De Punctorum Antiquitate</i>, 1.3.',
    'par. 1 cap. 6. See also Glassius, lib. 1 tract. 1. De Textus ': '<b>Modern Citation:</b> Johannes Buxtorf II, <i>De Punctorum Antiquitate</i>, 1.6; Salomon Glassius, <i>Philologia Sacra</i>, 1.1.',
    'Epistle to Evagrius, Epist. 126: "Nec refert utrum Salem an Salim nominetur, ': '<b>Modern Citation:</b> Jerome, <i>Epistle 126 to Evagrius</i>.',
    'De Punct. Orig. par. 1 p. 13, 14, cap. 3;': '<b>Modern Citation:</b> Johannes Buxtorf II, <i>De Punctorum Origine</i>, 1.3, pp. 13-14.',
    'Censur. in Exercitat. 4 cap. 7 p. 17;': '<b>Modern Citation:</b> Author, <i>Censura in Exercitationes</i>, 4.7, p. 17.',
    'Assert. Verit. Heb. cap. 5, "Dicesve me haec omnia mutuatum a Buxtorfio? q': '<b>Modern Citation:</b> Author, <i>Assertio Veritatis Hebraicae</i>, 5.',
    'Lib. Cosri. 1, par. 3, p. 28.': '<b>Modern Citation:</b> Judah Halevi, <i>Kuzari</i>, 1.3, p. 28.',
    'De Heb. Text. Sincer., Exer. 1 cap. 4 p. 40.': '<b>Modern Citation:</b> Author, <i>De Hebraici Textus Sinceritate Exercitationes</i>, 1.4, p. 40.',
    'Scal. ad Euseb. fol. 123; Wouwer Syntag. cap. 11.': '<b>Modern Citation:</b> Joseph Justus Scaliger, <i>Animadversiones in Chronologica Eusebii</i>, fol. 123; Johann Wouwer, <i>Syntagma de Graeca et Latina Bibliorum Interpretatione</i>, 11.',
    'Drusius, Observat. lib. 6 cap. 9.: —  [[BLOCKQUOTE]] "Vulgatam translationem Gra': '<b>Modern Citation:</b> Joannes Drusius, <i>Observationes Sacrae</i>, 6.9.',
    'lib. 2 De Verbo Dei, cap. 6.': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Verbo Dei</i>, 2.6.',
    'second book of his Apology against Rufinus, cap. 8:9,': '<b>Modern Citation:</b> Jerome, <i>Apology against Rufinus</i>, 2.8-9.',
    'lib. 2 De Invent, cap. 54. It is, say they, "In ratione bene considerata': '<b>Modern Citation:</b> Cicero, <i>De Inventione</i>, 2.54.',
    'lib. 7 cap. 6, Eth. Nicom.,': '<b>Modern Citation:</b> Aristotle, <i>Nicomachean Ethics</i>, 7.6.',
    'lib. 10 cap. 9;': '<b>Modern Citation:</b> Aristotle, <i>Nicomachean Ethics</i>, 10.9.',
    'Nicom., lib. 7 cap. 9;': '<b>Modern Citation:</b> Aristotle, <i>Nicomachean Ethics</i>, 7.9.',
    'Bradwardin earnestly contends, lib. 2 De Cau. Dei. cap. 7, concluding his disputation, that [[BLOCKQUOTE]': '<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei</i>, 2.7.',
    'Thomas, lib. 3 Con. Genesis cap. ely.;': '<b>Modern Citation:</b> Thomas Aquinas, <i>Summa Contra Gentiles</i>, 3.ely.',
    'lib. 2 cap. 8, Corol.,  [[BLOCKQUOTE]] "Sieur secundum primi ': '<b>Modern Citation:</b> Author, <i>Book 2</i>, 8, Corol.',
    'Eusebius, Ecclesiastes Hist., and Hierom, Lib. de Script.,': '<b>Modern Citation:</b> Eusebius, <i>Ecclesiastical History</i>, and Jerome, <i>De Viris Illustribus</i>.',
    'Hegesippus, in Eusebius Hist. Ecclesiastes, lib. 3 cap. 32: Ως ἄρα μέχρι τῶν τότε χρόνων, παρθένος καθαρὰ': '<b>Modern Citation:</b> Hegesippus, cited in Eusebius, <i>Ecclesiastical History</i>, 3.32.',
    'Epist. ad August.,': '<b>Modern Citation:</b> Jerome, <i>Epistle to Augustine</i>.',
    'second book de Grat. et Lib. Arbit. "Prater Scripturas adferunt alia testimoni': '<b>Modern Citation:</b> Robert Bellarmine, <i>De Gratia et Libero Arbitrio</i>, 2.',
    'Augustinus in Lib. de Bono Perseverantiae, veteres patres, qui ante ': '<b>Modern Citation:</b> Augustine, <i>De Bono Perseverantiae</i>.',
    'De Doctrin. Christiana, lib. 3 cap. 33.  Saith he,  [[BLOCKQUOTE]] "Non erat expertus': '<b>Modern Citation:</b> Augustine, <i>De Doctrina Christiana</i>, 3.33.',
    'Pererius, in Rom. cap. 8, disput. 22,': '<b>Modern Citation:</b> Benedictus Pererius, <i>Commentary on Romans</i>, 8, disp. 22.',
    '(Hist. Eccles., lib. 7 cap. 12),': '<b>Modern Citation:</b> Sozomen, <i>Ecclesiastical History</i>, 7.12.',
    'Dissert. de Episcop. 2 cap. 6 sect. 3," Canone apostolico secundo semper inte': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes de Episcopatu</i>, 2.6.3.',
    'lib. 6 cap. 14, they are brought in discoursing ἡμεις οῦν ἐπὶ': '<b>Modern Citation:</b> <i>Apostolic Constitutions</i>, 6.14.',
    'lib. 2 cap. 57, that the Acts written by Luke and read in the': '<b>Modern Citation:</b> <i>Apostolic Constitutions</i>, 2.57.',
    'lib. 8 cap. 4 (whereas the martyrdom of Stephen was before th': '<b>Modern Citation:</b> <i>Apostolic Constitutions</i>, 8.4.',
    'lib. 8 cap. 46. They tell us whom they appointed bishops of J': '<b>Modern Citation:</b> <i>Apostolic Constitutions</i>, 8.46.',
    'lib. 7 cap. 48. Nay, mention is made of Cerinthus, and that M': '<b>Modern Citation:</b> <i>Apostolic Constitutions</i>, 7.48.',
    'Lib. 5 cap. 28, salth he, "Quemadmodum quidam de nostr': '<b>Modern Citation:</b> Irenaeus, <i>Against Heresies</i>, 5.28.',
    'Dissert. 2 cap. 23, sect. 1, that Salmasius and Blondellus "morta': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.23.1.',
    'cap. 24 sect. 1, he would make us believe that these e': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.24.1.',
    'Specimen Consula. Animad. Heraldi., cap. 1 p. 19,  [[BLOCKQUOTE]] "Nuper quidem etiam nebu': '<b>Modern Citation:</b> Author, <i>Specimen Confutationis Animadversionum Heraldi</i>, 1, p. 19.',
    '(Dissert. 2 cap. 2 sect. 11)': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.2.11.',
    'cap. 8, being pressed with the testimony of the writer': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.8.',
    'Calv. Inst., lib. 1 cap. 13 sect. 29.  Whatever be the judgment of our doc': '<b>Modern Citation:</b> John Calvin, <i>Institutes of the Christian Religion</i>, 1.13.29.',
    'Cent. 2 cap. 10, De Episcop. Antioch. ac primum de Ignatio: — ': '<b>Modern Citation:</b> <i>Magdeburg Centuries</i>, Century 2, chap. 10.',
    'Dissert. 2 cap. 2 sect.  6. "Nulla," saith he, "quidem nobis incu': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.2.6.',
    'Ham. Dissert. 2 cap. 3;': '<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes</i>, 2.3.',
    'Epist. ad Tral. [cap. 2], whereunto is immediately subjo': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistle to the Trallians</i>, 2.',
    '[cap. 7] What the writer of this passage intended to ma': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistle to the Trallians</i>, 7.',
    'Epist. ad Magnes. [cap. 3] Πρέπον οῦν ἐστι καὶ ὑμᾶς ὑπακ': '<b>Modern Citation:</b> Ignatius of Antioch, <i>Epistle to the Magnesians</i>, 3.'
}
