CHUNK_DICT = {
    "[cap. 6:7]": "<b>Modern Citation:</b> Author, <i>Work</i>, cap. 6:7.",
    "Epist. ad Philadel. [cap. 5]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Philadelphenses</i>, cap. 5.",
    "[cap. 9]": "<b>Modern Citation:</b> Ignatius, <i>Epistola</i>, cap. 9.",
    "Lib. 2 cap. 2": "<b>Modern Citation:</b> <i>Constitutiones Apostolorum</i>, lib. 2, cap. 2.",
    "lib. 2 cap. 20.": "<b>Modern Citation:</b> <i>Constitutiones Apostolorum</i>, lib. 2, cap. 20.",
    "Dissert. 2 cap. 25, 7": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 2, cap. 25, sect. 7.",
    "Dissert. 4 cap. 7:8, 10.": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 4, cap. 7:8, 10.",
    "cap. 4 sect. 3": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, cap. 4, sect. 3.",
    "Dissert. 5 cap. 8 sect. 4": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 5, cap. 8, sect. 4.",
    "Dissert. 5 cap. 2 sect.  3.": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 5, cap. 2, sect. 3.",
    "cap. 1 sect. 24": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, cap. 1, sect. 24.",
    "Dissert. 4 cap. 10: ect.  9.": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 4, cap. 10, sect. 9.",
    "Dissert. 4 cap. 10 sect. 11": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 4, cap. 10, sect. 11.",
    "Dissert. 2 cap. 29 sect. 21, 22": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 2, cap. 29, sect. 21, 22.",
    "Epist. ad Eph.,": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Ephesios</i>.",
    "Dissert. 4 cap. 5": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, Dissert. 4, cap. 5.",
    "cap. 17:9.": "<b>Modern Citation:</b> Henry Hammond, <i>Dissertationes quatuor</i>, cap. 17:9.",
    "Act. 16:4; cum enim ζήτημα illud, cap. 15:2": "<b>Modern Citation:</b> <i>Acts</i> 16:4; 15:2.",
    "cap. 14:26, 15:3;": "<b>Modern Citation:</b> <i>Acts</i> 14:26; 15:3.",
    "ver. 41, cap. 16:4,": "<b>Modern Citation:</b> <i>Acts</i> 15:41; 16:4.",
    "Epist. ad Trall. cap. 8]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Trallianos</i>, cap. 8.",
    "Epist. ad. Philad. [cap. 9]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Philadelphenses</i>, cap. 9.",
    "Epist. ad Smyrn, [cap.1]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Smyrnaeos</i>, cap. 1.",
    "Epist. ad Smyrn. [cap. 4,]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Smyrnaeos</i>, cap. 4.",
    "Epist. ad Ephesians, [cap. 9]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Ephesios</i>, cap. 9.",
    "[cap. 14]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Ephesios</i>, cap. 14.",
    "[ad Romans cap. 7]": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Romanos</i>, cap. 7.",
    "Cypr. De Unit. Ecclesiastes [cap. 2]": "<b>Modern Citation:</b> Cyprian, <i>De Unitate Ecclesiae</i>, cap. 2.",
    "Basil, Lib. de Spir. Sanc. cap. 16": "<b>Modern Citation:</b> Basil of Caesarea, <i>De Spiritu Sancto</i>, cap. 16.",
    "MACARIUS AEgyptius, Homil. 5": "<b>Modern Citation:</b> Macarius of Egypt, <i>Homiliae spirituales</i>, Homil. 5.",
    "AMBROSE to this same purpose, lib. 1 cap. 6. De Jacob. et Vita Beat": "<b>Modern Citation:</b> Ambrose, <i>De Jacob et vita beata</i>, lib. 1, cap. 6.",
    "Prosper, cap. 2. De Ingrat.": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>De Ingratis</i>, cap. 2.",
    "Epist. ad Rusti.": "<b>Modern Citation:</b> Leo the Great, <i>Epistola ad Rusticum</i>.",
    "Caelestine, bishop of Rome, in his Epist. ad Gallos": "<b>Modern Citation:</b> Celestine I, <i>Epistola ad episcopos Galliarum</i>.",
    "Prosper, ad Collar, cap. 41": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>Contra Collatorem</i>, cap. 41.",
    "Leo, Epist. ad Concil. Arausic.": "<b>Modern Citation:</b> Leo the Great, <i>Epistola ad Concilium Arausicanum</i>.",
    "Jerome tells him, Epist. 94": "<b>Modern Citation:</b> Jerome, <i>Epistulae</i>, Epist. 94.",
    "Epist. Synod. Byzac.": "<b>Modern Citation:</b> <i>Epistola Synodica Byzacena</i>.",
    "on John, Homil. 53": "<b>Modern Citation:</b> Augustine, <i>Tractatus in Iohannis Evangelium</i>, Tract. 53.",
    "Prosper also presents it at large, cap. 25": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>Contra Collatorem</i>, cap. 25.",
    "Austin again, De Bono Persev., cap. 2": "<b>Modern Citation:</b> Augustine, <i>De Bono Perseverantiae</i>, cap. 2.",
    "cap. 6:9": "<b>Modern Citation:</b> Augustine, <i>De Bono Perseverantiae</i>, cap. 6:9.",
    "cap. 26": "<b>Modern Citation:</b> Augustine, <i>De Bono Perseverantiae</i>, cap. 26.",
    "De Correptione et Gratia, cap. 14": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 14.",
    "(cap. 12)": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 12.",
    "Bradwardin more confirms, De Cans. Dei, lib. 2 cap. 8 Coroll.": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, lib. 2, cap. 8, Coroll.",
    "De Correp. et Grat., cap. 11": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 11.",
    "cap. 12": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 12.",
    "De Predestinatione Sanc., cap. 17": "<b>Modern Citation:</b> Augustine, <i>De Praedestinatione Sanctorum</i>, cap. 17.",
    "cap. 9. De Bono Persev.": "<b>Modern Citation:</b> Augustine, <i>De Bono Perseverantiae</i>, cap. 9.",
    "Lib. de Correp. et Grat., cap. 12": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 12.",
    "De Correp. et Grat., cap. 9.": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 9.",
    "De Doct. Christiana, lib. 3 cap. 32": "<b>Modern Citation:</b> Augustine, <i>De Doctrina Christiana</i>, lib. 3, cap. 32.",
    "Prosper, ad cap. 7 Gal.:": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>Expositio Epistolae ad Galatas</i>, ad cap. 7.",
    "Austin before him, Epist. 42 and 47": "<b>Modern Citation:</b> Augustine, <i>Epistulae</i>, Epist. 42 and 47.",
    "GREGORY I., who, lib. 1 Epist. 99": "<b>Modern Citation:</b> Gregory the Great, <i>Epistulae</i>, lib. 1, Epist. 99.",
    "lib. 34. Moral, cap. 8.": "<b>Modern Citation:</b> Gregory the Great, <i>Moralia in Job</i>, lib. 34, cap. 8.",
    "in Epist. ad Ephesians cap. 1:14": "<b>Modern Citation:</b> John Chrysostom, <i>In Epistolam ad Ephesios</i>, cap. 1:14.",
    "Lib. 2, De Causa Dei, cap. 8": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, lib. 2, cap. 8.",
    "cap. 9, 10, 11": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, cap. 9, 10, 11.",
    "cap. 13": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, cap. 13.",
    "cap. 8, 9": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, cap. 8, 9.",
    "lib. 3 cap. 53.": "<b>Modern Citation:</b> Thomas Bradwardine, <i>De Causa Dei contra Pelagium</i>, lib. 3, cap. 53.",
    "lib. 2, De Grat. et Lib. Arbit. cap. 12": "<b>Modern Citation:</b> Author, <i>De Gratia et Libero Arbitrio</i>, lib. 2, cap. 12.",
    "Lib. 11 De Perpetuitat. vel Amis. Grat, cap. 2, sect. 6": "<b>Modern Citation:</b> Author, <i>De Perpetuitate vel Amissione Gratiae</i>, lib. 11, cap. 2, sect. 6.",
    "Mr. Goodwin tells us, cap. 9 sect. 7": "<b>Modern Citation:</b> John Goodwin, <i>Redemption Redeemed</i>, cap. 9, sect. 7.",
    "Prael. Theol. cap. 12 sect. 6": "<b>Modern Citation:</b> Faustus Socinus, <i>Praelectiones Theologicae</i>, cap. 12, sect. 6.",
    "Socinus, Prael. Theol. cap. 6": "<b>Modern Citation:</b> Faustus Socinus, <i>Praelectiones Theologicae</i>, cap. 6.",
    "Austin's mind, De Nup. et Concupis., cap. 8": "<b>Modern Citation:</b> Augustine, <i>De Nuptiis et Concupiscentia</i>, cap. 8.",
    "Constant., apud Socrat., lib. 1. cap. 10.": "<b>Modern Citation:</b> Constantine, in Socrates Scholasticus, <i>Historia Ecclesiastica</i>, lib. 1, cap. 10.",
    "Calvin, Institut. lib. 2, cap. 16": "<b>Modern Citation:</b> John Calvin, <i>Institutio Christianae Religionis</i>, lib. 2, cap. 16.",
    "Euseb. Hist. Eccles., lib. 4: cap. 15.": "<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, lib. 4, cap. 15.",
    "Epist. ad Philad. [cap. ix., A.D.": "<b>Modern Citation:</b> Ignatius, <i>Epistola ad Philadelphenses</i>, cap. 9.",
    "CYPRIAN, Epist. 62. to Caecilius": "<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, Epist. 62 ad Caecilium.",
    "Rivet. Crit. Sac. in Cyp. [lib. 2:cap. 15]": "<b>Modern Citation:</b> Andrew Rivet, <i>Critici Sacri</i>, in Cyprianum, lib. 2, cap. 15.",
    "Scultet.  Medul. Pat.": "<b>Modern Citation:</b> Abraham Scultetus, <i>Medulla Theologiae Patrum</i>.",
    "Erasm. praefat, ad lib.": "<b>Modern Citation:</b> Erasmus, <i>Praefatio ad librum</i>.",
    "AMBROSE de Vocat. Gen., lib. 1: cap. 3": "<b>Modern Citation:</b> Ambrose (Prosper of Aquitaine), <i>De Vocatione Omnium Gentium</i>, lib. 1, cap. 3.",
    "PROSPER, lib. 1:cap. 9": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>De Vocatione Omnium Gentium</i>, lib. 1, cap. 9.",
    "AUGUSTINE, de Cor. et Grat, cap. 40": "<b>Modern Citation:</b> Augustine, <i>De Correptione et Gratia</i>, cap. 40.",
    "Idem, Tract. lXXXvii, in Johan.:": "<b>Modern Citation:</b> Augustine, <i>Tractatus in Iohannis Evangelium</i>, Tract. 87.",
    "PROSPER [A.D. 440], Respon. ad Capit. Gall, cap. 9.:": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>Responsiones ad Capitula Objectionum Gallorum Calumniantium</i>, cap. 9.",
    "Idem, de Ingrat., cap. 9.:": "<b>Modern Citation:</b> Prosper of Aquitaine, <i>De Ingratis</i>, cap. 9.",
    "lib. in. cap. 4": "<b>Modern Citation:</b> John Owen, <i>The Death of Death in the Death of Christ</i>, lib. 3, cap. 4.",
    "lib. in cap. 8": "<b>Modern Citation:</b> John Owen, <i>The Death of Death in the Death of Christ</i>, lib. 3, cap. 8.",
    "lib. 2:cap. 1": "<b>Modern Citation:</b> John Owen, <i>The Death of Death in the Death of Christ</i>, lib. 2, cap. 1.",
    "lib. 2: cap. 2.": "<b>Modern Citation:</b> John Owen, <i>The Death of Death in the Death of Christ</i>, lib. 2, cap. 2.",
    "Ansel. de Verit. cap. 13": "<b>Modern Citation:</b> Anselm of Canterbury, <i>De Veritate</i>, cap. 13.",
    "Crellius adv. Groti. cap. i.": "<b>Modern Citation:</b> Johannes Crellius, <i>Responsio ad librum Hugonis Grotii quem de satisfactione Christi...</i>, cap. 1.",
    "lib. 3. cap. 7": "<b>Modern Citation:</b> Author, <i>Treatise</i>, lib. 3, cap. 7.",
    "Ethic. ad Nicom., lib. 5. cap. 1,2": "<b>Modern Citation:</b> Aristotle, <i>Ethica Nicomachea</i>, lib. 5, cap. 1, 2.",
    "Socinus de Serv. p. 3. cap. 8.": "<b>Modern Citation:</b> Faustus Socinus, <i>De Jesu Christo Servatore</i>, pars 3, cap. 8.",
    "Eusebius Pamphilus (Praep. Evang. lib. 4. cap. 16)": "<b>Modern Citation:</b> Eusebius Pamphilus, <i>Praeparatio Evangelica</i>, lib. 4, cap. 16.",
    "Ethic. Nicom. lib. 2. cap. 7.": "<b>Modern Citation:</b> Aristotle, <i>Ethica Nicomachea</i>, lib. 2, cap. 7."
}
