CHUNK_DICT = {
    'Epist. 57 ad Dardan., though he mentions it not. The rea': '<b>Modern Citation:</b> Jerome, <i>Epistulae</i>, 57 (ad Dardanum).',
    'lib. 7. epist. 63.  Alcuinus, Amatorius, Rabanus, Lib. P. P. tom. 10; with whom consent Walafridus Strab': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 63.',
    'Alcuinus, Amatorius, Rabanus, Lib. P. P. tom. 10; with whom consent Walafridus Strab': '<b>Modern Citation:</b> Alcuin, Amalarius, Rabanus, in <i>Bibliotheca Patrum</i>, vol. 10.',
    'Origen, Homil. 11. in Hierimes:  [[BLOCKQUOTE]] "Ubi frequenter ': '<b>Modern Citation:</b> Origen, <i>Homiliae in Jeremiam</i>, 11:',
    'Apol., cap.  30. again, cap. 39:  [[BLOCKQUOTE]] "Corpu': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 30.',
    'again, cap. 39:  [[BLOCKQUOTE]] "Corpu': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 39:',
    'Socrates on this matter, lib. 5 cap. 21. For these, then, the Lord Christ hath made pr': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 5.21.',
    'lib. 3 cap. 29. The greater deviations, which I intend, began': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 3.29.',
    'in 1 ad Timoth. cap. 5.  It seems there was some alteration in church ': '<b>Modern Citation:</b> Ambrose (Ambrosiaster), <i>In Epistolam ad Timotheum primam</i>, 5.',
    'Eusebius lib. 4 cap. 15. I think there can be no veneration due to a m': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.15.',
    'Eusebius, lib. 4 cap. 22.  The same rise had the schisms of the Novatia': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.22.',
    'Eusebius, lib. 4 cap. 26. But, as it falls out on such occasions, much ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.26.',
    'Hist., lib. 7 cap. 19.  At length this matter fell into the handling': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.19.',
    'Eusebius, lib. 5 cap. 23.  The noise hereof coming abroad unto other ch': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.23.',
    'lib. 3 cap. 3. By Eusebius it is termed μεγάλη καὶ θαυμασία, ': '<b>Modern Citation:</b> Irenaeus, <i>Adversus Haereses</i>, 3.3.',
    'Eccles. Hist., lib. 3 cap. 16. And again he calls it ἱκανωτάτην γραφήν, — a ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 3.16.',
    'lib. 5 cap. 7.  There is no doubt but some things in the writ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.7.',
    'Eusebius Ecclesiast. Hist., lib. 4 cap. 23. But yet, because these epistles are so earnes': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.23.',
    'Epist. ad Magnes. [cap. 7] This direction can be given u': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Magnesios</i>, 7.',
    'Philadelphians [cap. 2]: Οπου ὁ ποιμήν ἐστιν ἐκεῖ ὡς πρόβατα ἀκολουθεῖ': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Philadelphenses</i>, 2: "Οπου ὁ ποιμήν ἐστιν ἐκεῖ ὡς πρόβατα ἀκολουθεῖτε".',
    '[cap.4]: Θαῤῥῶν γράφω τῂ ἀξιοθέῳ ἀγάπῃ ὑμῶν παρακαλῶν ὑ': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Philadelphenses</i>, 8: "Θαῤῥῶν γράφω τῂ ἀξιοθέῳ ἀγάπῃ ὑμῶν παρακαλῶν ὑμᾶς μηδὲν κατ\' ἐρίθειαν πράσσειν".',
    '[cap. 10]: Πρέπον ἐστὶν ὑμῖν ὡς ἐκκλησίᾳ Θεοῦ χειροτονῆ': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Philadelphenses</i>, 10: "Πρέπον ἐστὶν ὑμῖν ὡς ἐκκλησίᾳ Θεοῦ χειροτονῆσαι διάκονον".',
    '[cap. 5]: Εἰ γὰρ ἑνὸς καὶ δευτέρου προσευχὴ τοσαύτην ἱσ': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Ephesios</i>, 5: "Εἰ γὰρ ἑνὸς καὶ δευτέρου προσευχὴ τοσαύτην ἱσχὺν ἔχει".',
    '[cap. 13]: Σπουδάζετε οῦν πυκνότερον συνέρχεσθαι ὅταν γ': '<b>Modern Citation:</b> Ignatius, <i>Epistula ad Ephesios</i>, 13: "Σπουδάζετε οῦν πυκνότερον συνέρχεσθαι ὅταν γὰρ".',
    'Eusebius, Hist., lib. 5 cap. 1. Their design in it is to give an account of th': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.1.',
    'cap. 4.  He is, indeed, in that epistle called a presb': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.4.',
    'Eusebius himself, cap. 8, affirming that he would give an account of the': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.8',
    'Justin Martyr, Apol. ad Genesis cap. 39. The description of a church h': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 39.',
    'Hist. Eccl., lib. 5 cap. 14. So the same was done afterward in the case of': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.14.',
    'lib. 7 cap. 27, 28, 29. And this care is still incumbent on e': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.27-29.',
    'Euseb., lib. 4 cap. 22; and Valentinus, Tertul ad Valentine, cap. 4; ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.22;',
    'Tertul ad Valentine, cap. 4; ': '<b>Modern Citation:</b> Tertullian, <i>Adversus Valentinianos</i>, 4;',
    'Epiphan. Haeres.  42. Mon': '<b>Modern Citation:</b> Epiphanius, <i>Panarion</i>, 42.',
    'Euseb., lib. 6 cap. 43, and Arius at Alexandria. Hence is that censur': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 6.43',
    'Lactantius, lib. 4 cap. 30:  [[BLOCKQUOTE]] "Ii quorum fides fuit lubrica': '<b>Modern Citation:</b> Lactantius, <i>Divinae Institutiones</i>, 4.30:',
    'Epist. 113, whereof many were in towns and cities having': '<b>Modern Citation:</b> Theodoret, <i>Epistulae</i>, 113',
    'Sozomen declares, lib. 6 cap. 20. So it is at this day in divers provinces belo': '<b>Modern Citation:</b> Sozomen, <i>Historia Ecclesiastica</i>, 6.20.',
    'Euseb., lib. 6 cap. 33. Who knows not with what diligence they watche': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 6.33.',
    'Clem. Pedag., lib. 3 cap.  12. If the reader would have an account of the l': '<b>Modern Citation:</b> Clement of Alexandria, <i>Paedagogus</i>, 3.12.',
    'Clem. Epist. ad Cor. pp. 2-4; Justin Mart. Apol. 2; Tertullian': '<b>Modern Citation:</b> Clement of Rome, <i>Epistula I ad Corinthios</i>, 2-4;',
    'Justin Mart. Apol. 2; Tertullian': '<b>Modern Citation:</b> Justin Martyr, <i>Apologia Secunda</i>;',
    'Tertullian in his Algol, and lib. 2 ad Uxor. e': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, and <i>Ad Uxorem</i> 2, and <i>De Cultu Feminarum</i>;',
    'Cyprian, Epist. 2 et 12; Euseb. Hist. lib. 9, cap. 8; Athanas. Ep': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 2 and 12;',
    'Euseb. Hist. lib. 9, cap. 8; Athanas. Ep': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 9.8;',
    'Athanas. Epist. ad Solit., et Epiphan. lib. 3 ': '<b>Modern Citation:</b> Athanasius, <i>Historia Arianorum ad Monachos</i>,',
    'et Epiphan. lib. 3 t. 2, sect. 24; and': '<b>Modern Citation:</b> Epiphanius, <i>Panarion</i>, 3.2.24;',
    'Eusebius, lib. 5 cap. 21-23; as also of the rule which then prevailed, ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.21-23;',
    'Socrates on this occasion, lib. 5 cap. 21, concerning the non-institution of any days of': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 5.21,',
    'Euseb., lib. 6 cap. 43; where also is reported the decree which they ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 6.43;',
    'Cyprian, Epist. 51, ad Antonianum. But because the church would n': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 51 (ad Antonianum).',
    'Cyprian ad Jubaianum, Epist. 71, Euseb., lib. 7 cap. 8. That which was most pr': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 71 (ad Jubaianum),',
    'Euseb., lib. 7 cap. 8. That which was most pr': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.8.',
    'Euseb. lib. 7 cap. 8, — was invented, to be subservient unto it, was': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.8,',
    'Epist. 51. On that false opinion and this frivolous pret': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, 51.',
    'Socrat., lib. 1 cap. 7 This error endeavored to be imposed on all chur': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 1.7',
    'lib. 3 cap. 6. Hence he was enraged against him, and filled a': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 3.6.',
    'Theod. Hist., lib. 1 cap. 8; and his followers quickly complied with the Ar': '<b>Modern Citation:</b> Theodoret, <i>Historia Ecclesiastica</i>, 1.8;',
    'lib. 4 cap. 10. Yea, he also ascribes unto him some foolish o': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 4.10.',
    'Socrat. Hist., lib. 2 cap. 3. These were his pretences of sanctity and purit': '<b>Modern Citation:</b> Socrates Scholasticus, <i>Historia Ecclesiastica</i>, 2.3.',
    'lib. 4 cap. 62.  I know not why he should give us such a seve': '<b>Modern Citation:</b> Augustine, <i>De Haeresibus</i>, 62.',
    'Euseb., lib. 7 cap. 22. But I speak of stated churches, with their wo': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 7.22.',
    'Euseb. lib. 4 cap.  15. So in the excellent epistle of the churches ': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 4.15.',
    'Euseb. lib. 5 cap. 1.  **4.** As for the church of Jerusalem in part': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.1.',
    'Clemens, Stromat. lib. 7, Augustin. Lib. de Ovib. cap. 15, and sundry others of the ancien': '<b>Modern Citation:</b> Clement of Alexandria, <i>Stromata</i>, 7,',
    'Augustin. Lib. de Ovib. cap. 15, and sundry others of the ancien': '<b>Modern Citation:</b> Augustine, <i>De Ovibus</i>, 15,',
    'lib. 3 Con. Cel, cap. 1; — "When many were converted unto Christianity,': '<b>Modern Citation:</b> Origen, <i>Contra Celsum</i>, 3.1;',
    'Beda, lib. 2 cap. 2. I know it may be rationally replied that Rome ': '<b>Modern Citation:</b> Bede, <i>Historia Ecclesiastica</i>, 2.2.',
    'August. de Civit. Dei, lib. 28 cap. ult. "Multi Christiani," saith he, "divos divasqu': '<b>Modern Citation:</b> Augustine, <i>De Civitate Dei</i>, 22.ult.',
    'Euseb. Eccleas. Hist., lib. 5 cap. 22-25. This is an early instance of a considerabl': '<b>Modern Citation:</b> Eusebius, <i>Historia Ecclesiastica</i>, 5.22-25.',
    'Tertullian, Apol. cap. 23. "Videte," saith he, "ne et hoc ad irreli': '<b>Modern Citation:</b> Tertullian, <i>Apologeticus</i>, 23.',
    'council of Sardis, Epist. ad Alexaud., expressly affirms that they dissuade': '<b>Modern Citation:</b> Council of Sardica, <i>Epistula ad Alexandrinos</i>,',
    'council at Toledo, cap. de Judae. distinct, 45: "Praecipit sancta synodus': '<b>Modern Citation:</b> Council of Toledo, <i>De Judaeis</i>, dist. 45:',
    'Ambrose declare himself to have done, Epist. 27; as did the rest of the sober, godly bishops o': '<b>Modern Citation:</b> Ambrose, <i>Epistulae</i>, 27;',
    'Epist. ad Cornel. Though the pretensions ot Cornelius an': '<b>Modern Citation:</b> Cyprian, <i>Epistulae</i>, ad Cornelium.',
    'ozomen tells you expressly that he did so, lib. 4 cap. 15; and so doth Athanasius, Epist. ad Solitarios,': '<b>Modern Citation:</b> Sozomen, <i>Historia Ecclesiastica</i>, 4.15;',
    'Athanasius, Epist. ad Solitarios,': '<b>Modern Citation:</b> Athanasius, <i>Historia Arianorum ad Monachos</i>,',
    'Cyprian condemns it, Epist. ad Demetriad. And so, generally, do all the fathe': '<b>Modern Citation:</b> Cyprian, <i>Ad Demetrianum</i>.',
    'Epist. ad Johan. Hierosol. Austin was of the same judgme': '<b>Modern Citation:</b> Jerome, <i>Epistula ad Johannem Hierosolymitanum</i>.',
    'Lib. de Morib. Ecclea Cathol. cap. 34. Your adoration ': '<b>Modern Citation:</b> Augustine, <i>De Moribus Ecclesiae Catholicae</i>, 34.',
}
